// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bdm5.proto

package bdm5

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 设备类型
type Device_DeviceType int32

const (
	Device_PHONE          Device_DeviceType = 1
	Device_TABLET         Device_DeviceType = 2
	Device_SMART_TV       Device_DeviceType = 3
	Device_OUTDOOR_SCREEN Device_DeviceType = 4
)

var Device_DeviceType_name = map[int32]string{
	1: "PHONE",
	2: "TABLET",
	3: "SMART_TV",
	4: "OUTDOOR_SCREEN",
}

var Device_DeviceType_value = map[string]int32{
	"PHONE":          1,
	"TABLET":         2,
	"SMART_TV":       3,
	"OUTDOOR_SCREEN": 4,
}

func (x Device_DeviceType) Enum() *Device_DeviceType {
	p := new(Device_DeviceType)
	*p = x
	return p
}

func (x Device_DeviceType) String() string {
	return proto.EnumName(Device_DeviceType_name, int32(x))
}

func (x *Device_DeviceType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_DeviceType_value, data, "Device_DeviceType")
	if err != nil {
		return err
	}
	*x = Device_DeviceType(value)
	return nil
}

func (Device_DeviceType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{4, 0}
}

// 操作系统类型
type Device_OsType int32

const (
	Device_ANDROID Device_OsType = 1
	Device_IOS     Device_OsType = 2
)

var Device_OsType_name = map[int32]string{
	1: "ANDROID",
	2: "IOS",
}

var Device_OsType_value = map[string]int32{
	"ANDROID": 1,
	"IOS":     2,
}

func (x Device_OsType) Enum() *Device_OsType {
	p := new(Device_OsType)
	*p = x
	return p
}

func (x Device_OsType) String() string {
	return proto.EnumName(Device_OsType_name, int32(x))
}

func (x *Device_OsType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Device_OsType_value, data, "Device_OsType")
	if err != nil {
		return err
	}
	*x = Device_OsType(value)
	return nil
}

func (Device_OsType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{4, 1}
}

// 网络连接类型
type Network_ConnectionType int32

const (
	Network_CONNECTION_UNKNOWN Network_ConnectionType = 0
	Network_CELL_UNKNOWN       Network_ConnectionType = 1
	Network_CELL_2G            Network_ConnectionType = 2
	Network_CELL_3G            Network_ConnectionType = 3
	Network_CELL_4G            Network_ConnectionType = 4
	Network_CELL_5G            Network_ConnectionType = 5
	Network_WIFI               Network_ConnectionType = 100
	Network_ETHERNET           Network_ConnectionType = 101
	Network_NEW_TYPE           Network_ConnectionType = 999
)

var Network_ConnectionType_name = map[int32]string{
	0:   "CONNECTION_UNKNOWN",
	1:   "CELL_UNKNOWN",
	2:   "CELL_2G",
	3:   "CELL_3G",
	4:   "CELL_4G",
	5:   "CELL_5G",
	100: "WIFI",
	101: "ETHERNET",
	999: "NEW_TYPE",
}

var Network_ConnectionType_value = map[string]int32{
	"CONNECTION_UNKNOWN": 0,
	"CELL_UNKNOWN":       1,
	"CELL_2G":            2,
	"CELL_3G":            3,
	"CELL_4G":            4,
	"CELL_5G":            5,
	"WIFI":               100,
	"ETHERNET":           101,
	"NEW_TYPE":           999,
}

func (x Network_ConnectionType) Enum() *Network_ConnectionType {
	p := new(Network_ConnectionType)
	*p = x
	return p
}

func (x Network_ConnectionType) String() string {
	return proto.EnumName(Network_ConnectionType_name, int32(x))
}

func (x *Network_ConnectionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Network_ConnectionType_value, data, "Network_ConnectionType")
	if err != nil {
		return err
	}
	*x = Network_ConnectionType(value)
	return nil
}

func (Network_ConnectionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{6, 0}
}

// 移动运营商类型
type Network_OperatorType int32

const (
	Network_UNKNOWN_OPERATOR Network_OperatorType = 0
	Network_CHINA_MOBILE     Network_OperatorType = 1
	Network_CHINA_TELECOM    Network_OperatorType = 2
	Network_CHINA_UNICOM     Network_OperatorType = 3
	Network_OTHER_OPERATOR   Network_OperatorType = 99
)

var Network_OperatorType_name = map[int32]string{
	0:  "UNKNOWN_OPERATOR",
	1:  "CHINA_MOBILE",
	2:  "CHINA_TELECOM",
	3:  "CHINA_UNICOM",
	99: "OTHER_OPERATOR",
}

var Network_OperatorType_value = map[string]int32{
	"UNKNOWN_OPERATOR": 0,
	"CHINA_MOBILE":     1,
	"CHINA_TELECOM":    2,
	"CHINA_UNICOM":     3,
	"OTHER_OPERATOR":   99,
}

func (x Network_OperatorType) Enum() *Network_OperatorType {
	p := new(Network_OperatorType)
	*p = x
	return p
}

func (x Network_OperatorType) String() string {
	return proto.EnumName(Network_OperatorType_name, int32(x))
}

func (x *Network_OperatorType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Network_OperatorType_value, data, "Network_OperatorType")
	if err != nil {
		return err
	}
	*x = Network_OperatorType(value)
	return nil
}

func (Network_OperatorType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{6, 1}
}

// GPS坐标类型
type Gps_CoordinateType int32

const (
	Gps_WGS84 Gps_CoordinateType = 1
	Gps_GCJ02 Gps_CoordinateType = 2
	Gps_BD09  Gps_CoordinateType = 3
)

var Gps_CoordinateType_name = map[int32]string{
	1: "WGS84",
	2: "GCJ02",
	3: "BD09",
}

var Gps_CoordinateType_value = map[string]int32{
	"WGS84": 1,
	"GCJ02": 2,
	"BD09":  3,
}

func (x Gps_CoordinateType) Enum() *Gps_CoordinateType {
	p := new(Gps_CoordinateType)
	*p = x
	return p
}

func (x Gps_CoordinateType) String() string {
	return proto.EnumName(Gps_CoordinateType_name, int32(x))
}

func (x *Gps_CoordinateType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Gps_CoordinateType_value, data, "Gps_CoordinateType")
	if err != nil {
		return err
	}
	*x = Gps_CoordinateType(value)
	return nil
}

func (Gps_CoordinateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{7, 0}
}

// 广告展示过程事件类型
type Tracking_TrackingEvent int32

const (
	// 广告展示过程共性事件
	Tracking_AD_CLICK    Tracking_TrackingEvent = 0
	Tracking_AD_EXPOSURE Tracking_TrackingEvent = 1
	Tracking_AD_CLOSE    Tracking_TrackingEvent = 2
	Tracking_SKIP        Tracking_TrackingEvent = 3
	Tracking_CLICK       Tracking_TrackingEvent = 4
	// 视频类广告展示过程事件
	Tracking_VIDEO_AD_START            Tracking_TrackingEvent = 101000
	Tracking_VIDEO_AD_FULL_SCREEN      Tracking_TrackingEvent = 101001
	Tracking_VIDEO_AD_END              Tracking_TrackingEvent = 101002
	Tracking_VIDEO_AD_START_CARD_CLICK Tracking_TrackingEvent = 101003
	// 下载类广告推广APP相关事件
	Tracking_APP_AD_DOWNLOAD_PAGE     Tracking_TrackingEvent = 102000
	Tracking_APP_AD_DOWNLOAD          Tracking_TrackingEvent = 102001
	Tracking_APP_AD_DOWNLOAD_BEGIN    Tracking_TrackingEvent = 102002
	Tracking_APP_AD_DOWNLOAD_PAUSE    Tracking_TrackingEvent = 102003
	Tracking_APP_AD_DOWNLOAD_CONTINUE Tracking_TrackingEvent = 102004
	Tracking_APP_AD_DOWNLOAD_FINISH   Tracking_TrackingEvent = 102005
	Tracking_APP_AD_INSTALL           Tracking_TrackingEvent = 102006
	Tracking_APP_AD_INSTALL_BEGIN     Tracking_TrackingEvent = 102007
	Tracking_APP_AD_INSTALL_PAUSE     Tracking_TrackingEvent = 102008
	Tracking_APP_AD_INSTALL_CONTINUE  Tracking_TrackingEvent = 102009
	Tracking_APP_AD_INSTALL_FINISH    Tracking_TrackingEvent = 102010
	Tracking_APP_AD_INSTALL_OPEN      Tracking_TrackingEvent = 102011
	Tracking_APP_AD_ACTIVE            Tracking_TrackingEvent = 102012
)

var Tracking_TrackingEvent_name = map[int32]string{
	0:      "AD_CLICK",
	1:      "AD_EXPOSURE",
	2:      "AD_CLOSE",
	3:      "SKIP",
	4:      "CLICK",
	101000: "VIDEO_AD_START",
	101001: "VIDEO_AD_FULL_SCREEN",
	101002: "VIDEO_AD_END",
	101003: "VIDEO_AD_START_CARD_CLICK",
	102000: "APP_AD_DOWNLOAD_PAGE",
	102001: "APP_AD_DOWNLOAD",
	102002: "APP_AD_DOWNLOAD_BEGIN",
	102003: "APP_AD_DOWNLOAD_PAUSE",
	102004: "APP_AD_DOWNLOAD_CONTINUE",
	102005: "APP_AD_DOWNLOAD_FINISH",
	102006: "APP_AD_INSTALL",
	102007: "APP_AD_INSTALL_BEGIN",
	102008: "APP_AD_INSTALL_PAUSE",
	102009: "APP_AD_INSTALL_CONTINUE",
	102010: "APP_AD_INSTALL_FINISH",
	102011: "APP_AD_INSTALL_OPEN",
	102012: "APP_AD_ACTIVE",
}

var Tracking_TrackingEvent_value = map[string]int32{
	"AD_CLICK":                  0,
	"AD_EXPOSURE":               1,
	"AD_CLOSE":                  2,
	"SKIP":                      3,
	"CLICK":                     4,
	"VIDEO_AD_START":            101000,
	"VIDEO_AD_FULL_SCREEN":      101001,
	"VIDEO_AD_END":              101002,
	"VIDEO_AD_START_CARD_CLICK": 101003,
	"APP_AD_DOWNLOAD_PAGE":      102000,
	"APP_AD_DOWNLOAD":           102001,
	"APP_AD_DOWNLOAD_BEGIN":     102002,
	"APP_AD_DOWNLOAD_PAUSE":     102003,
	"APP_AD_DOWNLOAD_CONTINUE":  102004,
	"APP_AD_DOWNLOAD_FINISH":    102005,
	"APP_AD_INSTALL":            102006,
	"APP_AD_INSTALL_BEGIN":      102007,
	"APP_AD_INSTALL_PAUSE":      102008,
	"APP_AD_INSTALL_CONTINUE":   102009,
	"APP_AD_INSTALL_FINISH":     102010,
	"APP_AD_INSTALL_OPEN":       102011,
	"APP_AD_ACTIVE":             102012,
}

func (x Tracking_TrackingEvent) Enum() *Tracking_TrackingEvent {
	p := new(Tracking_TrackingEvent)
	*p = x
	return p
}

func (x Tracking_TrackingEvent) String() string {
	return proto.EnumName(Tracking_TrackingEvent_name, int32(x))
}

func (x *Tracking_TrackingEvent) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Tracking_TrackingEvent_value, data, "Tracking_TrackingEvent")
	if err != nil {
		return err
	}
	*x = Tracking_TrackingEvent(value)
	return nil
}

func (Tracking_TrackingEvent) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{8, 0}
}

type Video_CopyRight int32

const (
	Video_CR_NONE  Video_CopyRight = 0
	Video_CR_EXIST Video_CopyRight = 1
	Video_CR_UGC   Video_CopyRight = 2
	Video_CR_OTHER Video_CopyRight = 3
)

var Video_CopyRight_name = map[int32]string{
	0: "CR_NONE",
	1: "CR_EXIST",
	2: "CR_UGC",
	3: "CR_OTHER",
}

var Video_CopyRight_value = map[string]int32{
	"CR_NONE":  0,
	"CR_EXIST": 1,
	"CR_UGC":   2,
	"CR_OTHER": 3,
}

func (x Video_CopyRight) Enum() *Video_CopyRight {
	p := new(Video_CopyRight)
	*p = x
	return p
}

func (x Video_CopyRight) String() string {
	return proto.EnumName(Video_CopyRight_name, int32(x))
}

func (x *Video_CopyRight) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Video_CopyRight_value, data, "Video_CopyRight")
	if err != nil {
		return err
	}
	*x = Video_CopyRight(value)
	return nil
}

func (Video_CopyRight) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{9, 0}
}

type Video_MaterialFormat int32

const (
	Video_VIDEO_TCL_MP4 Video_MaterialFormat = 11
	Video_VIDEO_TCL_TS  Video_MaterialFormat = 12
	Video_VIDEO_TS      Video_MaterialFormat = 13
)

var Video_MaterialFormat_name = map[int32]string{
	11: "VIDEO_TCL_MP4",
	12: "VIDEO_TCL_TS",
	13: "VIDEO_TS",
}

var Video_MaterialFormat_value = map[string]int32{
	"VIDEO_TCL_MP4": 11,
	"VIDEO_TCL_TS":  12,
	"VIDEO_TS":      13,
}

func (x Video_MaterialFormat) Enum() *Video_MaterialFormat {
	p := new(Video_MaterialFormat)
	*p = x
	return p
}

func (x Video_MaterialFormat) String() string {
	return proto.EnumName(Video_MaterialFormat_name, int32(x))
}

func (x *Video_MaterialFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Video_MaterialFormat_value, data, "Video_MaterialFormat")
	if err != nil {
		return err
	}
	*x = Video_MaterialFormat(value)
	return nil
}

func (Video_MaterialFormat) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{9, 1}
}

// 请求协议类型
type MobadsRequest_RequestProtocolType int32

const (
	MobadsRequest_UNKNOWN_PROTOCOL_TYPE MobadsRequest_RequestProtocolType = 0
	MobadsRequest_HTTP_PROTOCOL_TYPE    MobadsRequest_RequestProtocolType = 1
	MobadsRequest_HTTPS_PROTOCOL_TYPE   MobadsRequest_RequestProtocolType = 2
)

var MobadsRequest_RequestProtocolType_name = map[int32]string{
	0: "UNKNOWN_PROTOCOL_TYPE",
	1: "HTTP_PROTOCOL_TYPE",
	2: "HTTPS_PROTOCOL_TYPE",
}

var MobadsRequest_RequestProtocolType_value = map[string]int32{
	"UNKNOWN_PROTOCOL_TYPE": 0,
	"HTTP_PROTOCOL_TYPE":    1,
	"HTTPS_PROTOCOL_TYPE":   2,
}

func (x MobadsRequest_RequestProtocolType) Enum() *MobadsRequest_RequestProtocolType {
	p := new(MobadsRequest_RequestProtocolType)
	*p = x
	return p
}

func (x MobadsRequest_RequestProtocolType) String() string {
	return proto.EnumName(MobadsRequest_RequestProtocolType_name, int32(x))
}

func (x *MobadsRequest_RequestProtocolType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MobadsRequest_RequestProtocolType_value, data, "MobadsRequest_RequestProtocolType")
	if err != nil {
		return err
	}
	*x = MobadsRequest_RequestProtocolType(value)
	return nil
}

func (MobadsRequest_RequestProtocolType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{12, 0}
}

// 创意类型
type MaterialMeta_CreativeType int32

const (
	MaterialMeta_NO_TYPE   MaterialMeta_CreativeType = 0
	MaterialMeta_TEXT      MaterialMeta_CreativeType = 1
	MaterialMeta_IMAGE     MaterialMeta_CreativeType = 2
	MaterialMeta_TEXT_ICON MaterialMeta_CreativeType = 3
	MaterialMeta_VIDEO     MaterialMeta_CreativeType = 4
)

var MaterialMeta_CreativeType_name = map[int32]string{
	0: "NO_TYPE",
	1: "TEXT",
	2: "IMAGE",
	3: "TEXT_ICON",
	4: "VIDEO",
}

var MaterialMeta_CreativeType_value = map[string]int32{
	"NO_TYPE":   0,
	"TEXT":      1,
	"IMAGE":     2,
	"TEXT_ICON": 3,
	"VIDEO":     4,
}

func (x MaterialMeta_CreativeType) Enum() *MaterialMeta_CreativeType {
	p := new(MaterialMeta_CreativeType)
	*p = x
	return p
}

func (x MaterialMeta_CreativeType) String() string {
	return proto.EnumName(MaterialMeta_CreativeType_name, int32(x))
}

func (x *MaterialMeta_CreativeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MaterialMeta_CreativeType_value, data, "MaterialMeta_CreativeType")
	if err != nil {
		return err
	}
	*x = MaterialMeta_CreativeType(value)
	return nil
}

func (MaterialMeta_CreativeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{14, 0}
}

// 交互类型
type MaterialMeta_InteractionType int32

const (
	MaterialMeta_NO_INTERACTION MaterialMeta_InteractionType = 0
	MaterialMeta_SURFING        MaterialMeta_InteractionType = 1
	MaterialMeta_DOWNLOAD       MaterialMeta_InteractionType = 2
	MaterialMeta_DEEPLINK       MaterialMeta_InteractionType = 3
)

var MaterialMeta_InteractionType_name = map[int32]string{
	0: "NO_INTERACTION",
	1: "SURFING",
	2: "DOWNLOAD",
	3: "DEEPLINK",
}

var MaterialMeta_InteractionType_value = map[string]int32{
	"NO_INTERACTION": 0,
	"SURFING":        1,
	"DOWNLOAD":       2,
	"DEEPLINK":       3,
}

func (x MaterialMeta_InteractionType) Enum() *MaterialMeta_InteractionType {
	p := new(MaterialMeta_InteractionType)
	*p = x
	return p
}

func (x MaterialMeta_InteractionType) String() string {
	return proto.EnumName(MaterialMeta_InteractionType_name, int32(x))
}

func (x *MaterialMeta_InteractionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MaterialMeta_InteractionType_value, data, "MaterialMeta_InteractionType")
	if err != nil {
		return err
	}
	*x = MaterialMeta_InteractionType(value)
	return nil
}

func (MaterialMeta_InteractionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{14, 1}
}

// 版本号信息
type Version struct {
	Major                *uint32  `protobuf:"varint,1,opt,name=major,def=0" json:"major,omitempty"`
	Minor                *uint32  `protobuf:"varint,2,opt,name=minor,def=0" json:"minor,omitempty"`
	Micro                *uint32  `protobuf:"varint,3,opt,name=micro,def=0" json:"micro,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Version) Reset()         { *m = Version{} }
func (m *Version) String() string { return proto.CompactTextString(m) }
func (*Version) ProtoMessage()    {}
func (*Version) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{0}
}

func (m *Version) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Version.Unmarshal(m, b)
}
func (m *Version) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Version.Marshal(b, m, deterministic)
}
func (m *Version) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Version.Merge(m, src)
}
func (m *Version) XXX_Size() int {
	return xxx_messageInfo_Version.Size(m)
}
func (m *Version) XXX_DiscardUnknown() {
	xxx_messageInfo_Version.DiscardUnknown(m)
}

var xxx_messageInfo_Version proto.InternalMessageInfo

const Default_Version_Major uint32 = 0
const Default_Version_Minor uint32 = 0
const Default_Version_Micro uint32 = 0

func (m *Version) GetMajor() uint32 {
	if m != nil && m.Major != nil {
		return *m.Major
	}
	return Default_Version_Major
}

func (m *Version) GetMinor() uint32 {
	if m != nil && m.Minor != nil {
		return *m.Minor
	}
	return Default_Version_Minor
}

func (m *Version) GetMicro() uint32 {
	if m != nil && m.Micro != nil {
		return *m.Micro
	}
	return Default_Version_Micro
}

// 应用信息
type App struct {
	AppId                *string  `protobuf:"bytes,1,opt,name=app_id,json=appId,def=" json:"app_id,omitempty"`
	ChannelId            *string  `protobuf:"bytes,2,opt,name=channel_id,json=channelId" json:"channel_id,omitempty"`
	AppVersion           *Version `protobuf:"bytes,3,opt,name=app_version,json=appVersion" json:"app_version,omitempty"`
	AppPackage           *string  `protobuf:"bytes,4,opt,name=app_package,json=appPackage" json:"app_package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{1}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetAppId() string {
	if m != nil && m.AppId != nil {
		return *m.AppId
	}
	return ""
}

func (m *App) GetChannelId() string {
	if m != nil && m.ChannelId != nil {
		return *m.ChannelId
	}
	return ""
}

func (m *App) GetAppVersion() *Version {
	if m != nil {
		return m.AppVersion
	}
	return nil
}

func (m *App) GetAppPackage() string {
	if m != nil && m.AppPackage != nil {
		return *m.AppPackage
	}
	return ""
}

// 唯一用户标识，必需使用明文，必需按要求填写，具体填写指导详见接口说明文档
type UdId struct {
	Idfa                 *string  `protobuf:"bytes,1,opt,name=idfa,def=" json:"idfa,omitempty"`
	Imei                 *string  `protobuf:"bytes,2,opt,name=imei,def=" json:"imei,omitempty"`
	Mac                  *string  `protobuf:"bytes,3,opt,name=mac,def=" json:"mac,omitempty"`
	ImeiMd5              *string  `protobuf:"bytes,4,opt,name=imei_md5,json=imeiMd5,def=" json:"imei_md5,omitempty"`
	AndroidId            *string  `protobuf:"bytes,5,opt,name=android_id,json=androidId,def=" json:"android_id,omitempty"`
	Baiduid              *string  `protobuf:"bytes,6,opt,name=baiduid,def=" json:"baiduid,omitempty"`
	Cuid                 *string  `protobuf:"bytes,7,opt,name=cuid,def=" json:"cuid,omitempty"`
	IdfaMd5              *string  `protobuf:"bytes,8,opt,name=idfa_md5,json=idfaMd5,def=" json:"idfa_md5,omitempty"`
	AndroididMd5         *string  `protobuf:"bytes,9,opt,name=androidid_md5,json=androididMd5,def=" json:"androidid_md5,omitempty"`
	Passport             *string  `protobuf:"bytes,10,opt,name=passport,def=" json:"passport,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UdId) Reset()         { *m = UdId{} }
func (m *UdId) String() string { return proto.CompactTextString(m) }
func (*UdId) ProtoMessage()    {}
func (*UdId) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{2}
}

func (m *UdId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UdId.Unmarshal(m, b)
}
func (m *UdId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UdId.Marshal(b, m, deterministic)
}
func (m *UdId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UdId.Merge(m, src)
}
func (m *UdId) XXX_Size() int {
	return xxx_messageInfo_UdId.Size(m)
}
func (m *UdId) XXX_DiscardUnknown() {
	xxx_messageInfo_UdId.DiscardUnknown(m)
}

var xxx_messageInfo_UdId proto.InternalMessageInfo

func (m *UdId) GetIdfa() string {
	if m != nil && m.Idfa != nil {
		return *m.Idfa
	}
	return ""
}

func (m *UdId) GetImei() string {
	if m != nil && m.Imei != nil {
		return *m.Imei
	}
	return ""
}

func (m *UdId) GetMac() string {
	if m != nil && m.Mac != nil {
		return *m.Mac
	}
	return ""
}

func (m *UdId) GetImeiMd5() string {
	if m != nil && m.ImeiMd5 != nil {
		return *m.ImeiMd5
	}
	return ""
}

func (m *UdId) GetAndroidId() string {
	if m != nil && m.AndroidId != nil {
		return *m.AndroidId
	}
	return ""
}

func (m *UdId) GetBaiduid() string {
	if m != nil && m.Baiduid != nil {
		return *m.Baiduid
	}
	return ""
}

func (m *UdId) GetCuid() string {
	if m != nil && m.Cuid != nil {
		return *m.Cuid
	}
	return ""
}

func (m *UdId) GetIdfaMd5() string {
	if m != nil && m.IdfaMd5 != nil {
		return *m.IdfaMd5
	}
	return ""
}

func (m *UdId) GetAndroididMd5() string {
	if m != nil && m.AndroididMd5 != nil {
		return *m.AndroididMd5
	}
	return ""
}

func (m *UdId) GetPassport() string {
	if m != nil && m.Passport != nil {
		return *m.Passport
	}
	return ""
}

// 二维尺寸信息
type Size struct {
	Width                *uint32  `protobuf:"varint,1,opt,name=width,def=0" json:"width,omitempty"`
	Height               *uint32  `protobuf:"varint,2,opt,name=height,def=0" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Size) Reset()         { *m = Size{} }
func (m *Size) String() string { return proto.CompactTextString(m) }
func (*Size) ProtoMessage()    {}
func (*Size) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{3}
}

func (m *Size) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Size.Unmarshal(m, b)
}
func (m *Size) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Size.Marshal(b, m, deterministic)
}
func (m *Size) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Size.Merge(m, src)
}
func (m *Size) XXX_Size() int {
	return xxx_messageInfo_Size.Size(m)
}
func (m *Size) XXX_DiscardUnknown() {
	xxx_messageInfo_Size.DiscardUnknown(m)
}

var xxx_messageInfo_Size proto.InternalMessageInfo

const Default_Size_Width uint32 = 0
const Default_Size_Height uint32 = 0

func (m *Size) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return Default_Size_Width
}

func (m *Size) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return Default_Size_Height
}

// 设备信息
type Device struct {
	DeviceType           *Device_DeviceType `protobuf:"varint,1,opt,name=device_type,json=deviceType,enum=bdm5.Device_DeviceType" json:"device_type,omitempty"`
	OsType               *Device_OsType     `protobuf:"varint,2,opt,name=os_type,json=osType,enum=bdm5.Device_OsType" json:"os_type,omitempty"`
	OsVersion            *Version           `protobuf:"bytes,3,opt,name=os_version,json=osVersion" json:"os_version,omitempty"`
	Vendor               []byte             `protobuf:"bytes,4,opt,name=vendor,def=" json:"vendor,omitempty"`
	Model                []byte             `protobuf:"bytes,5,opt,name=model,def=" json:"model,omitempty"`
	Udid                 *UdId              `protobuf:"bytes,6,opt,name=udid" json:"udid,omitempty"`
	ScreenSize           *Size              `protobuf:"bytes,7,opt,name=screen_size,json=screenSize" json:"screen_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{4}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetDeviceType() Device_DeviceType {
	if m != nil && m.DeviceType != nil {
		return *m.DeviceType
	}
	return Device_PHONE
}

func (m *Device) GetOsType() Device_OsType {
	if m != nil && m.OsType != nil {
		return *m.OsType
	}
	return Device_ANDROID
}

func (m *Device) GetOsVersion() *Version {
	if m != nil {
		return m.OsVersion
	}
	return nil
}

func (m *Device) GetVendor() []byte {
	if m != nil {
		return m.Vendor
	}
	return nil
}

func (m *Device) GetModel() []byte {
	if m != nil {
		return m.Model
	}
	return nil
}

func (m *Device) GetUdid() *UdId {
	if m != nil {
		return m.Udid
	}
	return nil
}

func (m *Device) GetScreenSize() *Size {
	if m != nil {
		return m.ScreenSize
	}
	return nil
}

// WiFi热点信息
type WiFiAp struct {
	ApMac                *string  `protobuf:"bytes,1,opt,name=ap_mac,json=apMac" json:"ap_mac,omitempty"`
	Rssi                 *int32   `protobuf:"varint,2,opt,name=rssi" json:"rssi,omitempty"`
	ApName               []byte   `protobuf:"bytes,3,opt,name=ap_name,json=apName" json:"ap_name,omitempty"`
	IsConnected          *bool    `protobuf:"varint,4,opt,name=is_connected,json=isConnected" json:"is_connected,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WiFiAp) Reset()         { *m = WiFiAp{} }
func (m *WiFiAp) String() string { return proto.CompactTextString(m) }
func (*WiFiAp) ProtoMessage()    {}
func (*WiFiAp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{5}
}

func (m *WiFiAp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WiFiAp.Unmarshal(m, b)
}
func (m *WiFiAp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WiFiAp.Marshal(b, m, deterministic)
}
func (m *WiFiAp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WiFiAp.Merge(m, src)
}
func (m *WiFiAp) XXX_Size() int {
	return xxx_messageInfo_WiFiAp.Size(m)
}
func (m *WiFiAp) XXX_DiscardUnknown() {
	xxx_messageInfo_WiFiAp.DiscardUnknown(m)
}

var xxx_messageInfo_WiFiAp proto.InternalMessageInfo

func (m *WiFiAp) GetApMac() string {
	if m != nil && m.ApMac != nil {
		return *m.ApMac
	}
	return ""
}

func (m *WiFiAp) GetRssi() int32 {
	if m != nil && m.Rssi != nil {
		return *m.Rssi
	}
	return 0
}

func (m *WiFiAp) GetApName() []byte {
	if m != nil {
		return m.ApName
	}
	return nil
}

func (m *WiFiAp) GetIsConnected() bool {
	if m != nil && m.IsConnected != nil {
		return *m.IsConnected
	}
	return false
}

// 网络环境信息
type Network struct {
	Ipv4                 *string                 `protobuf:"bytes,1,opt,name=ipv4" json:"ipv4,omitempty"`
	ConnectionType       *Network_ConnectionType `protobuf:"varint,2,opt,name=connection_type,json=connectionType,enum=bdm5.Network_ConnectionType" json:"connection_type,omitempty"`
	OperatorType         *Network_OperatorType   `protobuf:"varint,3,opt,name=operator_type,json=operatorType,enum=bdm5.Network_OperatorType" json:"operator_type,omitempty"`
	CellularId           *string                 `protobuf:"bytes,4,opt,name=cellular_id,json=cellularId" json:"cellular_id,omitempty"`
	WifiAps              []*WiFiAp               `protobuf:"bytes,5,rep,name=wifi_aps,json=wifiAps" json:"wifi_aps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Network) Reset()         { *m = Network{} }
func (m *Network) String() string { return proto.CompactTextString(m) }
func (*Network) ProtoMessage()    {}
func (*Network) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{6}
}

func (m *Network) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Network.Unmarshal(m, b)
}
func (m *Network) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Network.Marshal(b, m, deterministic)
}
func (m *Network) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Network.Merge(m, src)
}
func (m *Network) XXX_Size() int {
	return xxx_messageInfo_Network.Size(m)
}
func (m *Network) XXX_DiscardUnknown() {
	xxx_messageInfo_Network.DiscardUnknown(m)
}

var xxx_messageInfo_Network proto.InternalMessageInfo

func (m *Network) GetIpv4() string {
	if m != nil && m.Ipv4 != nil {
		return *m.Ipv4
	}
	return ""
}

func (m *Network) GetConnectionType() Network_ConnectionType {
	if m != nil && m.ConnectionType != nil {
		return *m.ConnectionType
	}
	return Network_CONNECTION_UNKNOWN
}

func (m *Network) GetOperatorType() Network_OperatorType {
	if m != nil && m.OperatorType != nil {
		return *m.OperatorType
	}
	return Network_UNKNOWN_OPERATOR
}

func (m *Network) GetCellularId() string {
	if m != nil && m.CellularId != nil {
		return *m.CellularId
	}
	return ""
}

func (m *Network) GetWifiAps() []*WiFiAp {
	if m != nil {
		return m.WifiAps
	}
	return nil
}

// GPS信息
type Gps struct {
	CoordinateType       *Gps_CoordinateType `protobuf:"varint,1,opt,name=coordinate_type,json=coordinateType,enum=bdm5.Gps_CoordinateType" json:"coordinate_type,omitempty"`
	Longitude            *float64            `protobuf:"fixed64,2,opt,name=longitude" json:"longitude,omitempty"`
	Latitude             *float64            `protobuf:"fixed64,3,opt,name=latitude" json:"latitude,omitempty"`
	Timestamp            *uint32             `protobuf:"varint,4,opt,name=timestamp" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Gps) Reset()         { *m = Gps{} }
func (m *Gps) String() string { return proto.CompactTextString(m) }
func (*Gps) ProtoMessage()    {}
func (*Gps) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{7}
}

func (m *Gps) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gps.Unmarshal(m, b)
}
func (m *Gps) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gps.Marshal(b, m, deterministic)
}
func (m *Gps) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gps.Merge(m, src)
}
func (m *Gps) XXX_Size() int {
	return xxx_messageInfo_Gps.Size(m)
}
func (m *Gps) XXX_DiscardUnknown() {
	xxx_messageInfo_Gps.DiscardUnknown(m)
}

var xxx_messageInfo_Gps proto.InternalMessageInfo

func (m *Gps) GetCoordinateType() Gps_CoordinateType {
	if m != nil && m.CoordinateType != nil {
		return *m.CoordinateType
	}
	return Gps_WGS84
}

func (m *Gps) GetLongitude() float64 {
	if m != nil && m.Longitude != nil {
		return *m.Longitude
	}
	return 0
}

func (m *Gps) GetLatitude() float64 {
	if m != nil && m.Latitude != nil {
		return *m.Latitude
	}
	return 0
}

func (m *Gps) GetTimestamp() uint32 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

// 广告效果跟踪信息
type Tracking struct {
	TrackingEvent        *Tracking_TrackingEvent `protobuf:"varint,1,opt,name=tracking_event,json=trackingEvent,enum=bdm5.Tracking_TrackingEvent" json:"tracking_event,omitempty"`
	TrackingUrl          []string                `protobuf:"bytes,2,rep,name=tracking_url,json=trackingUrl" json:"tracking_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Tracking) Reset()         { *m = Tracking{} }
func (m *Tracking) String() string { return proto.CompactTextString(m) }
func (*Tracking) ProtoMessage()    {}
func (*Tracking) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{8}
}

func (m *Tracking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tracking.Unmarshal(m, b)
}
func (m *Tracking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tracking.Marshal(b, m, deterministic)
}
func (m *Tracking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tracking.Merge(m, src)
}
func (m *Tracking) XXX_Size() int {
	return xxx_messageInfo_Tracking.Size(m)
}
func (m *Tracking) XXX_DiscardUnknown() {
	xxx_messageInfo_Tracking.DiscardUnknown(m)
}

var xxx_messageInfo_Tracking proto.InternalMessageInfo

func (m *Tracking) GetTrackingEvent() Tracking_TrackingEvent {
	if m != nil && m.TrackingEvent != nil {
		return *m.TrackingEvent
	}
	return Tracking_AD_CLICK
}

func (m *Tracking) GetTrackingUrl() []string {
	if m != nil {
		return m.TrackingUrl
	}
	return nil
}

type Video struct {
	Title                []byte                 `protobuf:"bytes,1,opt,name=title" json:"title,omitempty"`
	ContentLength        *uint32                `protobuf:"varint,2,opt,name=content_length,json=contentLength" json:"content_length,omitempty"`
	Copyright            *Video_CopyRight       `protobuf:"varint,3,opt,name=copyright,enum=bdm5.Video_CopyRight" json:"copyright,omitempty"`
	MaterialFormat       []Video_MaterialFormat `protobuf:"varint,4,rep,name=material_format,json=materialFormat,enum=bdm5.Video_MaterialFormat" json:"material_format,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Video) Reset()         { *m = Video{} }
func (m *Video) String() string { return proto.CompactTextString(m) }
func (*Video) ProtoMessage()    {}
func (*Video) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{9}
}

func (m *Video) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Video.Unmarshal(m, b)
}
func (m *Video) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Video.Marshal(b, m, deterministic)
}
func (m *Video) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Video.Merge(m, src)
}
func (m *Video) XXX_Size() int {
	return xxx_messageInfo_Video.Size(m)
}
func (m *Video) XXX_DiscardUnknown() {
	xxx_messageInfo_Video.DiscardUnknown(m)
}

var xxx_messageInfo_Video proto.InternalMessageInfo

func (m *Video) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Video) GetContentLength() uint32 {
	if m != nil && m.ContentLength != nil {
		return *m.ContentLength
	}
	return 0
}

func (m *Video) GetCopyright() Video_CopyRight {
	if m != nil && m.Copyright != nil {
		return *m.Copyright
	}
	return Video_CR_NONE
}

func (m *Video) GetMaterialFormat() []Video_MaterialFormat {
	if m != nil {
		return m.MaterialFormat
	}
	return nil
}

type Page struct {
	Url                  []byte   `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Title                []byte   `protobuf:"bytes,2,opt,name=title" json:"title,omitempty"`
	SourceUrl            []byte   `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl" json:"source_url,omitempty"`
	ContentId            *string  `protobuf:"bytes,4,opt,name=content_id,json=contentId" json:"content_id,omitempty"`
	ContentCategory      [][]byte `protobuf:"bytes,5,rep,name=content_category,json=contentCategory" json:"content_category,omitempty"`
	ContentLabel         [][]byte `protobuf:"bytes,6,rep,name=content_label,json=contentLabel" json:"content_label,omitempty"`
	AuthorId             *string  `protobuf:"bytes,7,opt,name=author_id,json=authorId" json:"author_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{10}
}

func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (m *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(m, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetUrl() []byte {
	if m != nil {
		return m.Url
	}
	return nil
}

func (m *Page) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *Page) GetSourceUrl() []byte {
	if m != nil {
		return m.SourceUrl
	}
	return nil
}

func (m *Page) GetContentId() string {
	if m != nil && m.ContentId != nil {
		return *m.ContentId
	}
	return ""
}

func (m *Page) GetContentCategory() [][]byte {
	if m != nil {
		return m.ContentCategory
	}
	return nil
}

func (m *Page) GetContentLabel() [][]byte {
	if m != nil {
		return m.ContentLabel
	}
	return nil
}

func (m *Page) GetAuthorId() string {
	if m != nil && m.AuthorId != nil {
		return *m.AuthorId
	}
	return ""
}

// 广告位信息
type AdSlot struct {
	AdslotId             *string  `protobuf:"bytes,1,opt,name=adslot_id,json=adslotId" json:"adslot_id,omitempty"`
	AdslotSize           *Size    `protobuf:"bytes,2,opt,name=adslot_size,json=adslotSize" json:"adslot_size,omitempty"`
	Topics               [][]byte `protobuf:"bytes,3,rep,name=topics" json:"topics,omitempty"`
	Video                *Video   `protobuf:"bytes,4,opt,name=video" json:"video,omitempty"`
	Ctkey                *string  `protobuf:"bytes,5,opt,name=ctkey" json:"ctkey,omitempty"`
	SequenceId           *uint32  `protobuf:"varint,6,opt,name=sequence_id,json=sequenceId" json:"sequence_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdSlot) Reset()         { *m = AdSlot{} }
func (m *AdSlot) String() string { return proto.CompactTextString(m) }
func (*AdSlot) ProtoMessage()    {}
func (*AdSlot) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{11}
}

func (m *AdSlot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdSlot.Unmarshal(m, b)
}
func (m *AdSlot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdSlot.Marshal(b, m, deterministic)
}
func (m *AdSlot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdSlot.Merge(m, src)
}
func (m *AdSlot) XXX_Size() int {
	return xxx_messageInfo_AdSlot.Size(m)
}
func (m *AdSlot) XXX_DiscardUnknown() {
	xxx_messageInfo_AdSlot.DiscardUnknown(m)
}

var xxx_messageInfo_AdSlot proto.InternalMessageInfo

func (m *AdSlot) GetAdslotId() string {
	if m != nil && m.AdslotId != nil {
		return *m.AdslotId
	}
	return ""
}

func (m *AdSlot) GetAdslotSize() *Size {
	if m != nil {
		return m.AdslotSize
	}
	return nil
}

func (m *AdSlot) GetTopics() [][]byte {
	if m != nil {
		return m.Topics
	}
	return nil
}

func (m *AdSlot) GetVideo() *Video {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *AdSlot) GetCtkey() string {
	if m != nil && m.Ctkey != nil {
		return *m.Ctkey
	}
	return ""
}

func (m *AdSlot) GetSequenceId() uint32 {
	if m != nil && m.SequenceId != nil {
		return *m.SequenceId
	}
	return 0
}

// Baidu Mobads API请求
type MobadsRequest struct {
	RequestId            *string                            `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ApiVersion           *Version                           `protobuf:"bytes,2,opt,name=api_version,json=apiVersion" json:"api_version,omitempty"`
	App                  *App                               `protobuf:"bytes,3,opt,name=app" json:"app,omitempty"`
	Device               *Device                            `protobuf:"bytes,4,opt,name=device" json:"device,omitempty"`
	Network              *Network                           `protobuf:"bytes,5,opt,name=network" json:"network,omitempty"`
	Gps                  *Gps                               `protobuf:"bytes,6,opt,name=gps" json:"gps,omitempty"`
	Adslot               *AdSlot                            `protobuf:"bytes,7,opt,name=adslot" json:"adslot,omitempty"`
	IsDebug              *bool                              `protobuf:"varint,8,opt,name=is_debug,json=isDebug,def=0" json:"is_debug,omitempty"`
	RequestProtocolType  *MobadsRequest_RequestProtocolType `protobuf:"varint,9,opt,name=request_protocol_type,json=requestProtocolType,enum=bdm5.MobadsRequest_RequestProtocolType,def=1" json:"request_protocol_type,omitempty"`
	Page                 *Page                              `protobuf:"bytes,10,opt,name=page" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                           `json:"-"`
	XXX_unrecognized     []byte                             `json:"-"`
	XXX_sizecache        int32                              `json:"-"`
}

func (m *MobadsRequest) Reset()         { *m = MobadsRequest{} }
func (m *MobadsRequest) String() string { return proto.CompactTextString(m) }
func (*MobadsRequest) ProtoMessage()    {}
func (*MobadsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{12}
}

func (m *MobadsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobadsRequest.Unmarshal(m, b)
}
func (m *MobadsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobadsRequest.Marshal(b, m, deterministic)
}
func (m *MobadsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobadsRequest.Merge(m, src)
}
func (m *MobadsRequest) XXX_Size() int {
	return xxx_messageInfo_MobadsRequest.Size(m)
}
func (m *MobadsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MobadsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MobadsRequest proto.InternalMessageInfo

const Default_MobadsRequest_IsDebug bool = false
const Default_MobadsRequest_RequestProtocolType MobadsRequest_RequestProtocolType = MobadsRequest_HTTP_PROTOCOL_TYPE

func (m *MobadsRequest) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *MobadsRequest) GetApiVersion() *Version {
	if m != nil {
		return m.ApiVersion
	}
	return nil
}

func (m *MobadsRequest) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *MobadsRequest) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

func (m *MobadsRequest) GetNetwork() *Network {
	if m != nil {
		return m.Network
	}
	return nil
}

func (m *MobadsRequest) GetGps() *Gps {
	if m != nil {
		return m.Gps
	}
	return nil
}

func (m *MobadsRequest) GetAdslot() *AdSlot {
	if m != nil {
		return m.Adslot
	}
	return nil
}

func (m *MobadsRequest) GetIsDebug() bool {
	if m != nil && m.IsDebug != nil {
		return *m.IsDebug
	}
	return Default_MobadsRequest_IsDebug
}

func (m *MobadsRequest) GetRequestProtocolType() MobadsRequest_RequestProtocolType {
	if m != nil && m.RequestProtocolType != nil {
		return *m.RequestProtocolType
	}
	return Default_MobadsRequest_RequestProtocolType
}

func (m *MobadsRequest) GetPage() *Page {
	if m != nil {
		return m.Page
	}
	return nil
}

// 广告元数据组索引结构
// 一条广告可能包含多个物料元信息,我们统称这些元信息为广告元数据组
// 返回广告时，total_num表明当前广告包含的物料元数据个数，current_index表明当前的物料元数据在元数据组中的索引
// 请求多个广告返回时，ad_key唯一标识一个广告元数据组(一个广告)，MetaIndex标识一个元数据组中的每个元数据信息
type MetaIndex struct {
	TotalNum             *uint32  `protobuf:"varint,1,opt,name=total_num,json=totalNum" json:"total_num,omitempty"`
	CurrentIndex         *uint32  `protobuf:"varint,2,opt,name=current_index,json=currentIndex" json:"current_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MetaIndex) Reset()         { *m = MetaIndex{} }
func (m *MetaIndex) String() string { return proto.CompactTextString(m) }
func (*MetaIndex) ProtoMessage()    {}
func (*MetaIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{13}
}

func (m *MetaIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetaIndex.Unmarshal(m, b)
}
func (m *MetaIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetaIndex.Marshal(b, m, deterministic)
}
func (m *MetaIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetaIndex.Merge(m, src)
}
func (m *MetaIndex) XXX_Size() int {
	return xxx_messageInfo_MetaIndex.Size(m)
}
func (m *MetaIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_MetaIndex.DiscardUnknown(m)
}

var xxx_messageInfo_MetaIndex proto.InternalMessageInfo

func (m *MetaIndex) GetTotalNum() uint32 {
	if m != nil && m.TotalNum != nil {
		return *m.TotalNum
	}
	return 0
}

func (m *MetaIndex) GetCurrentIndex() uint32 {
	if m != nil && m.CurrentIndex != nil {
		return *m.CurrentIndex
	}
	return 0
}

// 广告物料元数据信息
type MaterialMeta struct {
	CreativeType         *MaterialMeta_CreativeType    `protobuf:"varint,1,opt,name=creative_type,json=creativeType,enum=bdm5.MaterialMeta_CreativeType" json:"creative_type,omitempty"`
	InteractionType      *MaterialMeta_InteractionType `protobuf:"varint,2,opt,name=interaction_type,json=interactionType,enum=bdm5.MaterialMeta_InteractionType" json:"interaction_type,omitempty"`
	WinNoticeUrl         []string                      `protobuf:"bytes,3,rep,name=win_notice_url,json=winNoticeUrl" json:"win_notice_url,omitempty"`
	ClickUrl             *string                       `protobuf:"bytes,4,opt,name=click_url,json=clickUrl" json:"click_url,omitempty"`
	Title                []byte                        `protobuf:"bytes,5,opt,name=title" json:"title,omitempty"`
	Description          [][]byte                      `protobuf:"bytes,6,rep,name=description" json:"description,omitempty"`
	IconSrc              []string                      `protobuf:"bytes,7,rep,name=icon_src,json=iconSrc" json:"icon_src,omitempty"`
	ImageSrc             []string                      `protobuf:"bytes,8,rep,name=image_src,json=imageSrc" json:"image_src,omitempty"`
	AppPackage           *string                       `protobuf:"bytes,9,opt,name=app_package,json=appPackage" json:"app_package,omitempty"`
	AppSize              *uint32                       `protobuf:"varint,10,opt,name=app_size,json=appSize" json:"app_size,omitempty"`
	VideoUrl             *string                       `protobuf:"bytes,11,opt,name=video_url,json=videoUrl" json:"video_url,omitempty"`
	VideoDuration        *uint32                       `protobuf:"varint,12,opt,name=video_duration,json=videoDuration" json:"video_duration,omitempty"`
	MetaIndex            *MetaIndex                    `protobuf:"bytes,13,opt,name=meta_index,json=metaIndex" json:"meta_index,omitempty"`
	MaterialWidth        *uint32                       `protobuf:"varint,14,opt,name=material_width,json=materialWidth" json:"material_width,omitempty"`
	MaterialHeight       *uint32                       `protobuf:"varint,15,opt,name=material_height,json=materialHeight" json:"material_height,omitempty"`
	BrandName            *string                       `protobuf:"bytes,16,opt,name=brand_name,json=brandName" json:"brand_name,omitempty"`
	AdTitle              *string                       `protobuf:"bytes,17,opt,name=ad_title,json=adTitle" json:"ad_title,omitempty"`
	MaterialSize         *uint32                       `protobuf:"varint,18,opt,name=material_size,json=materialSize" json:"material_size,omitempty"`
	DeeplinkUrl          []byte                        `protobuf:"bytes,19,opt,name=deeplink_url,json=deeplinkUrl" json:"deeplink_url,omitempty"`
	FallbackType         *uint32                       `protobuf:"varint,20,opt,name=fallback_type,json=fallbackType" json:"fallback_type,omitempty"`
	FallbackUrl          []byte                        `protobuf:"bytes,21,opt,name=fallback_url,json=fallbackUrl" json:"fallback_url,omitempty"`
	ApkName              *string                       `protobuf:"bytes,22,opt,name=apk_name,json=apkName" json:"apk_name,omitempty"`
	Rating               *float32                      `protobuf:"fixed32,23,opt,name=rating" json:"rating,omitempty"`
	Comments             *uint32                       `protobuf:"varint,24,opt,name=comments" json:"comments,omitempty"`
	ImageSize            *MaterialMeta_ImageSize       `protobuf:"bytes,25,opt,name=image_size,json=imageSize" json:"image_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *MaterialMeta) Reset()         { *m = MaterialMeta{} }
func (m *MaterialMeta) String() string { return proto.CompactTextString(m) }
func (*MaterialMeta) ProtoMessage()    {}
func (*MaterialMeta) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{14}
}

func (m *MaterialMeta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaterialMeta.Unmarshal(m, b)
}
func (m *MaterialMeta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaterialMeta.Marshal(b, m, deterministic)
}
func (m *MaterialMeta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaterialMeta.Merge(m, src)
}
func (m *MaterialMeta) XXX_Size() int {
	return xxx_messageInfo_MaterialMeta.Size(m)
}
func (m *MaterialMeta) XXX_DiscardUnknown() {
	xxx_messageInfo_MaterialMeta.DiscardUnknown(m)
}

var xxx_messageInfo_MaterialMeta proto.InternalMessageInfo

func (m *MaterialMeta) GetCreativeType() MaterialMeta_CreativeType {
	if m != nil && m.CreativeType != nil {
		return *m.CreativeType
	}
	return MaterialMeta_NO_TYPE
}

func (m *MaterialMeta) GetInteractionType() MaterialMeta_InteractionType {
	if m != nil && m.InteractionType != nil {
		return *m.InteractionType
	}
	return MaterialMeta_NO_INTERACTION
}

func (m *MaterialMeta) GetWinNoticeUrl() []string {
	if m != nil {
		return m.WinNoticeUrl
	}
	return nil
}

func (m *MaterialMeta) GetClickUrl() string {
	if m != nil && m.ClickUrl != nil {
		return *m.ClickUrl
	}
	return ""
}

func (m *MaterialMeta) GetTitle() []byte {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *MaterialMeta) GetDescription() [][]byte {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *MaterialMeta) GetIconSrc() []string {
	if m != nil {
		return m.IconSrc
	}
	return nil
}

func (m *MaterialMeta) GetImageSrc() []string {
	if m != nil {
		return m.ImageSrc
	}
	return nil
}

func (m *MaterialMeta) GetAppPackage() string {
	if m != nil && m.AppPackage != nil {
		return *m.AppPackage
	}
	return ""
}

func (m *MaterialMeta) GetAppSize() uint32 {
	if m != nil && m.AppSize != nil {
		return *m.AppSize
	}
	return 0
}

func (m *MaterialMeta) GetVideoUrl() string {
	if m != nil && m.VideoUrl != nil {
		return *m.VideoUrl
	}
	return ""
}

func (m *MaterialMeta) GetVideoDuration() uint32 {
	if m != nil && m.VideoDuration != nil {
		return *m.VideoDuration
	}
	return 0
}

func (m *MaterialMeta) GetMetaIndex() *MetaIndex {
	if m != nil {
		return m.MetaIndex
	}
	return nil
}

func (m *MaterialMeta) GetMaterialWidth() uint32 {
	if m != nil && m.MaterialWidth != nil {
		return *m.MaterialWidth
	}
	return 0
}

func (m *MaterialMeta) GetMaterialHeight() uint32 {
	if m != nil && m.MaterialHeight != nil {
		return *m.MaterialHeight
	}
	return 0
}

func (m *MaterialMeta) GetBrandName() string {
	if m != nil && m.BrandName != nil {
		return *m.BrandName
	}
	return ""
}

func (m *MaterialMeta) GetAdTitle() string {
	if m != nil && m.AdTitle != nil {
		return *m.AdTitle
	}
	return ""
}

func (m *MaterialMeta) GetMaterialSize() uint32 {
	if m != nil && m.MaterialSize != nil {
		return *m.MaterialSize
	}
	return 0
}

func (m *MaterialMeta) GetDeeplinkUrl() []byte {
	if m != nil {
		return m.DeeplinkUrl
	}
	return nil
}

func (m *MaterialMeta) GetFallbackType() uint32 {
	if m != nil && m.FallbackType != nil {
		return *m.FallbackType
	}
	return 0
}

func (m *MaterialMeta) GetFallbackUrl() []byte {
	if m != nil {
		return m.FallbackUrl
	}
	return nil
}

func (m *MaterialMeta) GetApkName() string {
	if m != nil && m.ApkName != nil {
		return *m.ApkName
	}
	return ""
}

func (m *MaterialMeta) GetRating() float32 {
	if m != nil && m.Rating != nil {
		return *m.Rating
	}
	return 0
}

func (m *MaterialMeta) GetComments() uint32 {
	if m != nil && m.Comments != nil {
		return *m.Comments
	}
	return 0
}

func (m *MaterialMeta) GetImageSize() *MaterialMeta_ImageSize {
	if m != nil {
		return m.ImageSize
	}
	return nil
}

// 图片物料尺寸，宽、高
type MaterialMeta_ImageSize struct {
	Width                *uint32  `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height               *uint32  `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MaterialMeta_ImageSize) Reset()         { *m = MaterialMeta_ImageSize{} }
func (m *MaterialMeta_ImageSize) String() string { return proto.CompactTextString(m) }
func (*MaterialMeta_ImageSize) ProtoMessage()    {}
func (*MaterialMeta_ImageSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{14, 0}
}

func (m *MaterialMeta_ImageSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MaterialMeta_ImageSize.Unmarshal(m, b)
}
func (m *MaterialMeta_ImageSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MaterialMeta_ImageSize.Marshal(b, m, deterministic)
}
func (m *MaterialMeta_ImageSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MaterialMeta_ImageSize.Merge(m, src)
}
func (m *MaterialMeta_ImageSize) XXX_Size() int {
	return xxx_messageInfo_MaterialMeta_ImageSize.Size(m)
}
func (m *MaterialMeta_ImageSize) XXX_DiscardUnknown() {
	xxx_messageInfo_MaterialMeta_ImageSize.DiscardUnknown(m)
}

var xxx_messageInfo_MaterialMeta_ImageSize proto.InternalMessageInfo

func (m *MaterialMeta_ImageSize) GetWidth() uint32 {
	if m != nil && m.Width != nil {
		return *m.Width
	}
	return 0
}

func (m *MaterialMeta_ImageSize) GetHeight() uint32 {
	if m != nil && m.Height != nil {
		return *m.Height
	}
	return 0
}

// 广告信息
// 同时填充material_meta和meta_group
// 建议使用meta_group，当前为兼容方案，后续版本将合并material_meta和meta_group为meta_group
type Ad struct {
	AdslotId             *string         `protobuf:"bytes,1,opt,name=adslot_id,json=adslotId" json:"adslot_id,omitempty"`
	HtmlSnippet          []byte          `protobuf:"bytes,2,opt,name=html_snippet,json=htmlSnippet" json:"html_snippet,omitempty"`
	MaterialMeta         *MaterialMeta   `protobuf:"bytes,3,opt,name=material_meta,json=materialMeta" json:"material_meta,omitempty"`
	AdKey                *string         `protobuf:"bytes,4,opt,name=ad_key,json=adKey" json:"ad_key,omitempty"`
	AdTracking           []*Tracking     `protobuf:"bytes,5,rep,name=ad_tracking,json=adTracking" json:"ad_tracking,omitempty"`
	MetaGroup            []*MaterialMeta `protobuf:"bytes,6,rep,name=meta_group,json=metaGroup" json:"meta_group,omitempty"`
	MobAdtext            *string         `protobuf:"bytes,7,opt,name=mob_adtext,json=mobAdtext" json:"mob_adtext,omitempty"`
	MobAdlogo            *string         `protobuf:"bytes,8,opt,name=mob_adlogo,json=mobAdlogo" json:"mob_adlogo,omitempty"`
	CpmBid               *uint32         `protobuf:"varint,9,opt,name=cpm_bid,json=cpmBid" json:"cpm_bid,omitempty"`
	Md5                  *string         `protobuf:"bytes,10,opt,name=md5" json:"md5,omitempty"`
	AdslotType           *uint32         `protobuf:"varint,11,opt,name=adslot_type,json=adslotType" json:"adslot_type,omitempty"`
	ChargeType           *uint32         `protobuf:"varint,12,opt,name=charge_type,json=chargeType" json:"charge_type,omitempty"`
	BuyerId              *uint32         `protobuf:"varint,13,opt,name=buyer_id,json=buyerId" json:"buyer_id,omitempty"`
	AntiTag              *int32          `protobuf:"varint,14,opt,name=anti_tag,json=antiTag" json:"anti_tag,omitempty"`
	StartTime            *uint64         `protobuf:"varint,15,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime              *uint64         `protobuf:"varint,16,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Ad) Reset()         { *m = Ad{} }
func (m *Ad) String() string { return proto.CompactTextString(m) }
func (*Ad) ProtoMessage()    {}
func (*Ad) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{15}
}

func (m *Ad) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ad.Unmarshal(m, b)
}
func (m *Ad) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ad.Marshal(b, m, deterministic)
}
func (m *Ad) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ad.Merge(m, src)
}
func (m *Ad) XXX_Size() int {
	return xxx_messageInfo_Ad.Size(m)
}
func (m *Ad) XXX_DiscardUnknown() {
	xxx_messageInfo_Ad.DiscardUnknown(m)
}

var xxx_messageInfo_Ad proto.InternalMessageInfo

func (m *Ad) GetAdslotId() string {
	if m != nil && m.AdslotId != nil {
		return *m.AdslotId
	}
	return ""
}

func (m *Ad) GetHtmlSnippet() []byte {
	if m != nil {
		return m.HtmlSnippet
	}
	return nil
}

func (m *Ad) GetMaterialMeta() *MaterialMeta {
	if m != nil {
		return m.MaterialMeta
	}
	return nil
}

func (m *Ad) GetAdKey() string {
	if m != nil && m.AdKey != nil {
		return *m.AdKey
	}
	return ""
}

func (m *Ad) GetAdTracking() []*Tracking {
	if m != nil {
		return m.AdTracking
	}
	return nil
}

func (m *Ad) GetMetaGroup() []*MaterialMeta {
	if m != nil {
		return m.MetaGroup
	}
	return nil
}

func (m *Ad) GetMobAdtext() string {
	if m != nil && m.MobAdtext != nil {
		return *m.MobAdtext
	}
	return ""
}

func (m *Ad) GetMobAdlogo() string {
	if m != nil && m.MobAdlogo != nil {
		return *m.MobAdlogo
	}
	return ""
}

func (m *Ad) GetCpmBid() uint32 {
	if m != nil && m.CpmBid != nil {
		return *m.CpmBid
	}
	return 0
}

func (m *Ad) GetMd5() string {
	if m != nil && m.Md5 != nil {
		return *m.Md5
	}
	return ""
}

func (m *Ad) GetAdslotType() uint32 {
	if m != nil && m.AdslotType != nil {
		return *m.AdslotType
	}
	return 0
}

func (m *Ad) GetChargeType() uint32 {
	if m != nil && m.ChargeType != nil {
		return *m.ChargeType
	}
	return 0
}

func (m *Ad) GetBuyerId() uint32 {
	if m != nil && m.BuyerId != nil {
		return *m.BuyerId
	}
	return 0
}

func (m *Ad) GetAntiTag() int32 {
	if m != nil && m.AntiTag != nil {
		return *m.AntiTag
	}
	return 0
}

func (m *Ad) GetStartTime() uint64 {
	if m != nil && m.StartTime != nil {
		return *m.StartTime
	}
	return 0
}

func (m *Ad) GetEndTime() uint64 {
	if m != nil && m.EndTime != nil {
		return *m.EndTime
	}
	return 0
}

// Baidu Mobads API应答
type MobadsResponse struct {
	RequestId            *string  `protobuf:"bytes,1,opt,name=request_id,json=requestId" json:"request_id,omitempty"`
	ErrorCode            *uint64  `protobuf:"varint,2,opt,name=error_code,json=errorCode" json:"error_code,omitempty"`
	Ads                  []*Ad    `protobuf:"bytes,3,rep,name=ads" json:"ads,omitempty"`
	ExpirationTime       *uint32  `protobuf:"varint,4,opt,name=expiration_time,json=expirationTime" json:"expiration_time,omitempty"`
	SearchKey            *string  `protobuf:"bytes,5,opt,name=search_key,json=searchKey" json:"search_key,omitempty"`
	ExtStyle             []byte   `protobuf:"bytes,6,opt,name=ext_style,json=extStyle" json:"ext_style,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MobadsResponse) Reset()         { *m = MobadsResponse{} }
func (m *MobadsResponse) String() string { return proto.CompactTextString(m) }
func (*MobadsResponse) ProtoMessage()    {}
func (*MobadsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_c6c07b2dff59dce0, []int{16}
}

func (m *MobadsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MobadsResponse.Unmarshal(m, b)
}
func (m *MobadsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MobadsResponse.Marshal(b, m, deterministic)
}
func (m *MobadsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MobadsResponse.Merge(m, src)
}
func (m *MobadsResponse) XXX_Size() int {
	return xxx_messageInfo_MobadsResponse.Size(m)
}
func (m *MobadsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MobadsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MobadsResponse proto.InternalMessageInfo

func (m *MobadsResponse) GetRequestId() string {
	if m != nil && m.RequestId != nil {
		return *m.RequestId
	}
	return ""
}

func (m *MobadsResponse) GetErrorCode() uint64 {
	if m != nil && m.ErrorCode != nil {
		return *m.ErrorCode
	}
	return 0
}

func (m *MobadsResponse) GetAds() []*Ad {
	if m != nil {
		return m.Ads
	}
	return nil
}

func (m *MobadsResponse) GetExpirationTime() uint32 {
	if m != nil && m.ExpirationTime != nil {
		return *m.ExpirationTime
	}
	return 0
}

func (m *MobadsResponse) GetSearchKey() string {
	if m != nil && m.SearchKey != nil {
		return *m.SearchKey
	}
	return ""
}

func (m *MobadsResponse) GetExtStyle() []byte {
	if m != nil {
		return m.ExtStyle
	}
	return nil
}

func init() {
	proto.RegisterEnum("bdm5.Device_DeviceType", Device_DeviceType_name, Device_DeviceType_value)
	proto.RegisterEnum("bdm5.Device_OsType", Device_OsType_name, Device_OsType_value)
	proto.RegisterEnum("bdm5.Network_ConnectionType", Network_ConnectionType_name, Network_ConnectionType_value)
	proto.RegisterEnum("bdm5.Network_OperatorType", Network_OperatorType_name, Network_OperatorType_value)
	proto.RegisterEnum("bdm5.Gps_CoordinateType", Gps_CoordinateType_name, Gps_CoordinateType_value)
	proto.RegisterEnum("bdm5.Tracking_TrackingEvent", Tracking_TrackingEvent_name, Tracking_TrackingEvent_value)
	proto.RegisterEnum("bdm5.Video_CopyRight", Video_CopyRight_name, Video_CopyRight_value)
	proto.RegisterEnum("bdm5.Video_MaterialFormat", Video_MaterialFormat_name, Video_MaterialFormat_value)
	proto.RegisterEnum("bdm5.MobadsRequest_RequestProtocolType", MobadsRequest_RequestProtocolType_name, MobadsRequest_RequestProtocolType_value)
	proto.RegisterEnum("bdm5.MaterialMeta_CreativeType", MaterialMeta_CreativeType_name, MaterialMeta_CreativeType_value)
	proto.RegisterEnum("bdm5.MaterialMeta_InteractionType", MaterialMeta_InteractionType_name, MaterialMeta_InteractionType_value)
	proto.RegisterType((*Version)(nil), "bdm5.Version")
	proto.RegisterType((*App)(nil), "bdm5.App")
	proto.RegisterType((*UdId)(nil), "bdm5.UdId")
	proto.RegisterType((*Size)(nil), "bdm5.Size")
	proto.RegisterType((*Device)(nil), "bdm5.Device")
	proto.RegisterType((*WiFiAp)(nil), "bdm5.WiFiAp")
	proto.RegisterType((*Network)(nil), "bdm5.Network")
	proto.RegisterType((*Gps)(nil), "bdm5.Gps")
	proto.RegisterType((*Tracking)(nil), "bdm5.Tracking")
	proto.RegisterType((*Video)(nil), "bdm5.Video")
	proto.RegisterType((*Page)(nil), "bdm5.Page")
	proto.RegisterType((*AdSlot)(nil), "bdm5.AdSlot")
	proto.RegisterType((*MobadsRequest)(nil), "bdm5.MobadsRequest")
	proto.RegisterType((*MetaIndex)(nil), "bdm5.MetaIndex")
	proto.RegisterType((*MaterialMeta)(nil), "bdm5.MaterialMeta")
	proto.RegisterType((*MaterialMeta_ImageSize)(nil), "bdm5.MaterialMeta.ImageSize")
	proto.RegisterType((*Ad)(nil), "bdm5.Ad")
	proto.RegisterType((*MobadsResponse)(nil), "bdm5.MobadsResponse")
}

func init() { proto.RegisterFile("bdm5.proto", fileDescriptor_c6c07b2dff59dce0) }

var fileDescriptor_c6c07b2dff59dce0 = []byte{
	// 2765 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x58, 0x4b, 0x73, 0xdb, 0xc8,
	0xf1, 0x17, 0xdf, 0x44, 0x93, 0x94, 0xb0, 0x63, 0xcb, 0xa2, 0x5f, 0x6b, 0x9b, 0xbb, 0x2e, 0xfb,
	0x5f, 0xff, 0x94, 0xe2, 0x68, 0xed, 0xca, 0xae, 0x73, 0x48, 0x68, 0x12, 0x96, 0xb1, 0xa6, 0x00,
	0xd6, 0x10, 0xb2, 0x37, 0x27, 0xd4, 0x08, 0x18, 0x53, 0x88, 0x48, 0x00, 0x01, 0x40, 0xdb, 0xda,
	0x6b, 0x72, 0xc8, 0xa3, 0x2a, 0x87, 0xa4, 0x5c, 0x95, 0x83, 0x72, 0xca, 0x57, 0x49, 0xce, 0xa9,
	0xca, 0x2d, 0x9f, 0x20, 0xd7, 0xbc, 0xb3, 0x79, 0x1c, 0x52, 0x3d, 0x33, 0x00, 0x49, 0xd9, 0xd9,
	0x9c, 0x88, 0xfe, 0x75, 0x4f, 0xcf, 0x4c, 0x77, 0x4f, 0x3f, 0x08, 0x70, 0xe4, 0xcf, 0x1f, 0xec,
	0xc6, 0x49, 0x94, 0x45, 0xa4, 0x8a, 0xdf, 0x3d, 0x07, 0x1a, 0xcf, 0x78, 0x92, 0x06, 0x51, 0x48,
	0x76, 0xa0, 0x36, 0x67, 0xdf, 0x89, 0x92, 0x6e, 0xe9, 0x66, 0xe9, 0x6e, 0xe7, 0x61, 0xe9, 0x1e,
	0x95, 0xb4, 0x60, 0x04, 0x61, 0x94, 0x74, 0xcb, 0x4b, 0x06, 0xd2, 0x92, 0xe1, 0x25, 0x51, 0xb7,
	0xb2, 0xc2, 0xf0, 0x92, 0xa8, 0xf7, 0x93, 0x12, 0x54, 0xfa, 0x71, 0x4c, 0x76, 0xa0, 0xce, 0xe2,
	0xd8, 0x0d, 0x7c, 0xa1, 0x53, 0x7b, 0xb8, 0x41, 0x6b, 0x2c, 0x8e, 0x4d, 0x9f, 0x5c, 0x07, 0xf0,
	0x8e, 0x59, 0x18, 0xf2, 0x19, 0x32, 0x51, 0xaf, 0x46, 0x35, 0x85, 0x98, 0x3e, 0xd9, 0x85, 0x16,
	0xae, 0x7b, 0x29, 0x4f, 0x26, 0xd4, 0xb7, 0xf6, 0x3a, 0xbb, 0xe2, 0xf4, 0xea, 0xb8, 0x14, 0x58,
	0x1c, 0xe7, 0x47, 0xbf, 0x21, 0xe5, 0x63, 0xe6, 0x9d, 0xb0, 0x29, 0xef, 0x56, 0x85, 0x3e, 0x14,
	0x18, 0x4b, 0xa4, 0xf7, 0xf3, 0x32, 0x54, 0x0f, 0x7d, 0xd3, 0x27, 0x17, 0xa1, 0x1a, 0xf8, 0x2f,
	0x58, 0x71, 0x1e, 0x41, 0x09, 0x74, 0xce, 0x03, 0x79, 0x10, 0x81, 0xce, 0x79, 0x40, 0x08, 0x54,
	0xe6, 0xcc, 0x13, 0xbb, 0x23, 0x88, 0x04, 0xb9, 0x0a, 0x4d, 0xe4, 0xb9, 0x73, 0xff, 0x81, 0xdc,
	0xe6, 0xe1, 0x06, 0x6d, 0x20, 0x72, 0xe0, 0x3f, 0x20, 0x37, 0x00, 0x58, 0xe8, 0x27, 0x51, 0xe0,
	0xe3, 0xad, 0x6a, 0x8a, 0xad, 0x29, 0xcc, 0xf4, 0xc9, 0x15, 0x68, 0x1c, 0xb1, 0xc0, 0x5f, 0x04,
	0x7e, 0xb7, 0x9e, 0x2f, 0x56, 0x00, 0x9e, 0xc1, 0x43, 0x46, 0x23, 0x3f, 0x03, 0x52, 0x62, 0x3f,
	0xff, 0x05, 0x13, 0xfb, 0x35, 0x8b, 0xfd, 0xfc, 0x17, 0x0c, 0xf7, 0xbb, 0x0d, 0x1d, 0xa5, 0x3b,
	0xf0, 0x85, 0x84, 0xa6, 0x24, 0xda, 0x05, 0x8c, 0x62, 0xd7, 0xa0, 0x19, 0xb3, 0x34, 0x8d, 0xa3,
	0x24, 0xeb, 0x82, 0x92, 0x28, 0x90, 0xde, 0x43, 0xa8, 0x4e, 0x82, 0xcf, 0x39, 0x3a, 0xf3, 0x55,
	0xe0, 0x67, 0xc7, 0x2b, 0xee, 0x17, 0x34, 0xb9, 0x0c, 0xf5, 0x63, 0x1e, 0x4c, 0x8f, 0xb3, 0xa5,
	0xff, 0x15, 0xd0, 0xfb, 0x7e, 0x05, 0xea, 0x43, 0xfe, 0x32, 0xf0, 0x38, 0xf9, 0x18, 0x5a, 0xbe,
	0xf8, 0x72, 0xb3, 0xd3, 0x98, 0x0b, 0x25, 0x9b, 0x7b, 0x3b, 0xd2, 0x65, 0x52, 0x44, 0xfd, 0x38,
	0xa7, 0x31, 0xa7, 0xe0, 0x17, 0xdf, 0xe4, 0x2b, 0xd0, 0x88, 0x52, 0xb9, 0xaa, 0x2c, 0x56, 0x5d,
	0x58, 0x5b, 0x65, 0xa7, 0x62, 0x45, 0x3d, 0x4a, 0x95, 0x34, 0x44, 0xe9, 0x97, 0x47, 0x86, 0x16,
	0xa5, 0x79, 0x60, 0x74, 0xa1, 0xfe, 0x92, 0x87, 0x7e, 0x94, 0x08, 0x67, 0xb5, 0x1f, 0x6e, 0x50,
	0x45, 0x93, 0x4b, 0x50, 0x9b, 0x47, 0x3e, 0x9f, 0x09, 0x37, 0x21, 0x43, 0x92, 0xe4, 0x7d, 0xa8,
	0x2e, 0x7c, 0xe5, 0x9f, 0xd6, 0x1e, 0x48, 0xcd, 0x18, 0x3a, 0x54, 0xe0, 0xe4, 0xff, 0xa1, 0x95,
	0x7a, 0x09, 0xe7, 0xa1, 0x9b, 0x06, 0x9f, 0x73, 0xe1, 0xad, 0x42, 0x0c, 0xed, 0x48, 0x41, 0xb2,
	0xf1, 0xbb, 0x67, 0x00, 0x2c, 0x2f, 0x4d, 0x34, 0xa8, 0x8d, 0x9f, 0xd8, 0x96, 0xa1, 0x97, 0x08,
	0x40, 0xdd, 0xe9, 0x3f, 0x1a, 0x19, 0x8e, 0x5e, 0x26, 0x6d, 0x68, 0x4e, 0x0e, 0xfa, 0xd4, 0x71,
	0x9d, 0x67, 0x7a, 0x85, 0x10, 0xd8, 0xb4, 0x0f, 0x9d, 0xa1, 0x6d, 0x53, 0x77, 0x32, 0xa0, 0x86,
	0x61, 0xe9, 0xd5, 0xde, 0xfb, 0x50, 0x97, 0x56, 0x20, 0x2d, 0x68, 0xf4, 0xad, 0x21, 0xb5, 0xcd,
	0xa1, 0x5e, 0x22, 0x0d, 0xa8, 0x98, 0xf6, 0x44, 0x2f, 0xf7, 0x22, 0xa8, 0x3f, 0x0f, 0x1e, 0x07,
	0xfd, 0x98, 0x6c, 0xe3, 0x83, 0x73, 0x31, 0x6a, 0x45, 0x80, 0xe3, 0x73, 0x3b, 0x60, 0x1e, 0x21,
	0x50, 0x4d, 0xd2, 0x54, 0xc6, 0x77, 0x8d, 0x8a, 0x6f, 0xb2, 0x03, 0x0d, 0x16, 0xbb, 0x21, 0x9b,
	0x73, 0x61, 0xc5, 0x36, 0xad, 0xb3, 0xd8, 0x62, 0x73, 0x4e, 0x6e, 0x41, 0x3b, 0x48, 0x5d, 0x2f,
	0x0a, 0x43, 0xee, 0x65, 0xdc, 0x17, 0x96, 0x6b, 0xd2, 0x56, 0x90, 0x0e, 0x72, 0xa8, 0xf7, 0x45,
	0x05, 0x1a, 0x16, 0xcf, 0x5e, 0x45, 0xc9, 0x09, 0xea, 0x0e, 0xe2, 0x97, 0xf7, 0xd5, 0x86, 0xe2,
	0x9b, 0x18, 0xb0, 0xa5, 0xd6, 0x07, 0x51, 0xb8, 0xea, 0xda, 0x6b, 0xd2, 0x50, 0x6a, 0xed, 0xee,
	0xa0, 0x10, 0x12, 0x3e, 0xde, 0xf4, 0xd6, 0x68, 0xf2, 0x4d, 0xe8, 0x44, 0x31, 0x4f, 0x58, 0x16,
	0x25, 0x52, 0x49, 0x45, 0x28, 0xb9, 0xb2, 0xae, 0xc4, 0x56, 0x22, 0x42, 0x45, 0x3b, 0x5a, 0xa1,
	0x30, 0x2f, 0x78, 0x7c, 0x36, 0x5b, 0xcc, 0x58, 0x82, 0x2f, 0x52, 0xe5, 0x85, 0x1c, 0x32, 0x7d,
	0x72, 0x07, 0x9a, 0xaf, 0x82, 0x17, 0x81, 0xcb, 0xe2, 0xb4, 0x5b, 0xbb, 0x59, 0xb9, 0xdb, 0xda,
	0x6b, 0x4b, 0xe5, 0xd2, 0x9e, 0xb4, 0x81, 0xdc, 0x7e, 0x9c, 0xf6, 0xde, 0x94, 0x60, 0x73, 0xfd,
	0xb4, 0xe4, 0x12, 0x90, 0x81, 0x6d, 0x59, 0xc6, 0xc0, 0x31, 0x6d, 0xcb, 0x3d, 0xb4, 0x9e, 0x5a,
	0xf6, 0x73, 0x4b, 0xdf, 0x20, 0x3a, 0xb4, 0x07, 0xc6, 0x68, 0x54, 0x20, 0x25, 0xf4, 0x9a, 0x40,
	0xf6, 0xf6, 0xf5, 0x72, 0x41, 0x7c, 0xb4, 0xaf, 0x57, 0x0a, 0xe2, 0xfe, 0xbe, 0x5e, 0x2d, 0x88,
	0x07, 0xfb, 0x7a, 0x8d, 0x34, 0xa1, 0xfa, 0xdc, 0x7c, 0x6c, 0xea, 0x3e, 0xc6, 0x87, 0xe1, 0x3c,
	0x31, 0xa8, 0x65, 0x38, 0x3a, 0x27, 0x1d, 0x68, 0x5a, 0xc6, 0x73, 0xd7, 0xf9, 0xf6, 0xd8, 0xd0,
	0x7f, 0xdf, 0xe8, 0x45, 0xd0, 0x5e, 0xbd, 0x3f, 0xb9, 0x08, 0xba, 0xda, 0xd7, 0xb5, 0xc7, 0x06,
	0xed, 0x3b, 0x36, 0x55, 0x47, 0x7a, 0x62, 0x5a, 0x7d, 0xf7, 0xc0, 0x7e, 0x64, 0x8e, 0x30, 0x00,
	0xdf, 0x83, 0x8e, 0x44, 0x1c, 0x63, 0x64, 0x0c, 0xec, 0x03, 0xbd, 0xbc, 0x14, 0x3a, 0xb4, 0x4c,
	0x44, 0x64, 0x2c, 0xe2, 0xce, 0x4b, 0x55, 0x5e, 0xef, 0xb7, 0x25, 0xa8, 0xec, 0xc7, 0x29, 0xe9,
	0xa3, 0x8b, 0xa3, 0xc4, 0x0f, 0x42, 0x96, 0xad, 0xbd, 0xf9, 0xae, 0x34, 0xe0, 0x7e, 0x9c, 0xee,
	0x0e, 0x0a, 0x81, 0xdc, 0xbd, 0xab, 0x34, 0xb9, 0x06, 0xda, 0x2c, 0x0a, 0xa7, 0x41, 0xb6, 0xf0,
	0x65, 0x7c, 0x94, 0xe8, 0x12, 0x20, 0x57, 0xa0, 0x39, 0x63, 0x99, 0x64, 0x56, 0x04, 0xb3, 0xa0,
	0x71, 0x65, 0x16, 0xcc, 0x79, 0x9a, 0xb1, 0x79, 0x2c, 0xbc, 0xda, 0xa1, 0x4b, 0xa0, 0x77, 0x0f,
	0x5d, 0xb5, 0xb6, 0x93, 0x06, 0xb5, 0xe7, 0xfb, 0x93, 0x8f, 0xef, 0xeb, 0x25, 0xfc, 0xdc, 0x1f,
	0x7c, 0x7a, 0x6f, 0x4f, 0x2f, 0xa3, 0x89, 0x1f, 0x0d, 0xef, 0x7d, 0xa2, 0x57, 0x7a, 0x3f, 0xad,
	0x41, 0xd3, 0x49, 0x98, 0x77, 0x12, 0x84, 0x53, 0x32, 0x80, 0xcd, 0x4c, 0x7d, 0xbb, 0xfc, 0x25,
	0x0f, 0x33, 0x75, 0x31, 0x15, 0xbb, 0xb9, 0x5c, 0xf1, 0x61, 0xa0, 0x0c, 0xed, 0x64, 0xab, 0x24,
	0x3e, 0xa2, 0x42, 0xc9, 0x22, 0x99, 0x75, 0xcb, 0x37, 0x2b, 0x77, 0x35, 0xda, 0xca, 0xb1, 0xc3,
	0x64, 0xd6, 0xfb, 0x45, 0x15, 0x3a, 0x6b, 0x3a, 0xd0, 0xd3, 0xfd, 0xa1, 0x3b, 0x18, 0x99, 0x83,
	0xa7, 0xfa, 0x06, 0xd9, 0x82, 0x56, 0x7f, 0xe8, 0x1a, 0x9f, 0x8d, 0xed, 0xc9, 0x21, 0x45, 0x9f,
	0xe5, 0x6c, 0x7b, 0x62, 0xc8, 0xd3, 0x4f, 0x9e, 0x9a, 0x63, 0xbd, 0x82, 0x57, 0x92, 0x6b, 0xaa,
	0xe4, 0x22, 0x6c, 0x3e, 0x33, 0x87, 0x86, 0xed, 0xf6, 0x87, 0xee, 0xc4, 0xe9, 0x53, 0x47, 0xff,
	0xc1, 0x9b, 0x3a, 0xb9, 0x02, 0x17, 0x0b, 0xf4, 0xf1, 0xe1, 0x68, 0x94, 0x67, 0x96, 0x1f, 0xbe,
	0xa9, 0x13, 0x02, 0xed, 0x82, 0x67, 0x58, 0x43, 0xfd, 0x47, 0x6f, 0xea, 0xe4, 0x06, 0x5c, 0x5e,
	0xd7, 0xe2, 0x0e, 0xfa, 0x34, 0x3f, 0xd8, 0x8f, 0xa5, 0xc2, 0xfe, 0x78, 0x8c, 0xec, 0xa1, 0xfd,
	0xdc, 0x1a, 0xd9, 0xfd, 0xa1, 0x3b, 0xee, 0xef, 0x1b, 0xfa, 0x1f, 0xce, 0xea, 0x64, 0x1b, 0xb6,
	0xce, 0xf1, 0xf4, 0x3f, 0x9e, 0xd5, 0xc9, 0x55, 0xd8, 0x3e, 0xbf, 0xe4, 0x91, 0xb1, 0x6f, 0x5a,
	0xfa, 0x9f, 0xde, 0xcd, 0x1c, 0xf7, 0x0f, 0x27, 0x86, 0xfe, 0xe7, 0xb3, 0x3a, 0x79, 0x1f, 0xba,
	0xe7, 0x99, 0x03, 0xdb, 0x72, 0x4c, 0xeb, 0xd0, 0xd0, 0xff, 0x72, 0x56, 0x27, 0xd7, 0xe0, 0xd2,
	0x79, 0xfe, 0x63, 0xd3, 0x32, 0x27, 0x4f, 0xf4, 0xbf, 0x9e, 0xd5, 0xd1, 0x22, 0x8a, 0x6b, 0x5a,
	0x13, 0xa7, 0x3f, 0x1a, 0xe9, 0x7f, 0x3b, 0x5b, 0xbd, 0x80, 0x42, 0xd5, 0x61, 0xfe, 0xfe, 0x4e,
	0x9e, 0x3c, 0xcb, 0x17, 0x67, 0x75, 0x72, 0x1d, 0x76, 0xce, 0xf1, 0x8a, 0xa3, 0xfc, 0x63, 0xed,
	0x1e, 0x39, 0x5b, 0x9d, 0xe4, 0x9f, 0x67, 0x75, 0x72, 0x19, 0x2e, 0x9c, 0x63, 0xda, 0x63, 0xc3,
	0xd2, 0xff, 0x75, 0x56, 0x27, 0x17, 0xa0, 0xa3, 0x58, 0xfd, 0x81, 0x63, 0x3e, 0x33, 0xf4, 0x7f,
	0x9f, 0xd5, 0x7b, 0xbf, 0x2e, 0x43, 0xed, 0x59, 0xe0, 0xf3, 0x88, 0x5c, 0x84, 0x5a, 0x16, 0x64,
	0x33, 0xf9, 0xc2, 0xda, 0x54, 0x12, 0xe4, 0x36, 0x60, 0xbe, 0xcc, 0x78, 0x98, 0xb9, 0x33, 0x1e,
	0x4e, 0xb3, 0x63, 0x59, 0x9f, 0x69, 0x47, 0xa1, 0x23, 0x01, 0x92, 0x8f, 0x40, 0xf3, 0xa2, 0xf8,
	0x34, 0x11, 0x15, 0x5c, 0x26, 0xd0, 0x6d, 0x55, 0x2f, 0x51, 0xf9, 0xee, 0x20, 0x8a, 0x4f, 0x29,
	0x32, 0xe9, 0x52, 0x8e, 0x0c, 0x60, 0x6b, 0xce, 0x32, 0x9e, 0x04, 0x6c, 0xe6, 0xbe, 0x88, 0x92,
	0x39, 0xcb, 0xba, 0xd5, 0x9b, 0x95, 0x65, 0xee, 0x95, 0x4b, 0x0f, 0x94, 0xc8, 0x63, 0x21, 0x41,
	0x37, 0xe7, 0x6b, 0x74, 0xef, 0x5b, 0xa0, 0x15, 0xca, 0x45, 0x72, 0xa3, 0xae, 0x85, 0xe5, 0x6f,
	0x03, 0x23, 0x79, 0x40, 0x5d, 0xe3, 0x33, 0x73, 0xe2, 0xc8, 0x62, 0x38, 0xa0, 0xee, 0xe1, 0xfe,
	0x40, 0x16, 0xc3, 0x01, 0x75, 0x45, 0xd6, 0xd1, 0x2b, 0xbd, 0x01, 0x6c, 0xae, 0xef, 0x81, 0x79,
	0x4b, 0x86, 0xa6, 0x33, 0x18, 0xb9, 0x07, 0xe3, 0xfb, 0x7a, 0x0b, 0xf3, 0xd6, 0x12, 0x72, 0x26,
	0x7a, 0x1b, 0x95, 0x28, 0x64, 0xa2, 0x77, 0x7a, 0xbf, 0x2b, 0x41, 0x75, 0xcc, 0xa6, 0x9c, 0xe8,
	0x50, 0xc1, 0xa7, 0x28, 0x8d, 0x88, 0x9f, 0x4b, 0xc3, 0x96, 0x57, 0x0d, 0x7b, 0x1d, 0x20, 0x8d,
	0x16, 0x89, 0xc7, 0xc5, 0xcb, 0x95, 0xc5, 0x51, 0x93, 0xc8, 0x61, 0x32, 0x13, 0xbd, 0xab, 0xb2,
	0x7b, 0x51, 0x53, 0x34, 0x85, 0x98, 0x3e, 0xf9, 0x3f, 0xd0, 0x73, 0xb6, 0xc7, 0x32, 0x3e, 0x8d,
	0x92, 0x53, 0x51, 0x5a, 0xda, 0x74, 0x4b, 0xe1, 0x03, 0x05, 0x93, 0x0f, 0xa0, 0x53, 0x78, 0x90,
	0x1d, 0xf1, 0x59, 0xb7, 0x2e, 0xe4, 0xda, 0xb9, 0x03, 0x11, 0x23, 0x57, 0x41, 0x63, 0x8b, 0xec,
	0x38, 0x12, 0x15, 0x4c, 0x34, 0x87, 0xb4, 0x29, 0x01, 0xd3, 0xef, 0xfd, 0xaa, 0x04, 0xf5, 0xbe,
	0x3f, 0x99, 0x45, 0x99, 0x90, 0xf3, 0xd3, 0x59, 0x94, 0x15, 0xed, 0x36, 0x6d, 0x4a, 0xc0, 0x14,
	0x5d, 0x8b, 0x62, 0x8a, 0xae, 0xa5, 0xfc, 0x76, 0xd7, 0x22, 0xd9, 0xa2, 0x13, 0xbc, 0x04, 0xf5,
	0x2c, 0x8a, 0x03, 0x2f, 0xed, 0x56, 0xc4, 0x79, 0x14, 0x45, 0x6e, 0x41, 0xed, 0x25, 0xfa, 0x5d,
	0xdc, 0xb9, 0xb5, 0xd7, 0x5a, 0x09, 0x05, 0x2a, 0x39, 0x68, 0x50, 0x2f, 0x3b, 0xe1, 0xa7, 0xb2,
	0xf9, 0xa5, 0x92, 0xc0, 0x32, 0x9c, 0xf2, 0xef, 0x2e, 0x78, 0xe8, 0x71, 0x57, 0xb5, 0x56, 0x1d,
	0x0a, 0x39, 0x64, 0xfa, 0xbd, 0x5f, 0x56, 0xa1, 0x73, 0x10, 0x1d, 0x31, 0x3f, 0xa5, 0x08, 0xa6,
	0x19, 0x1a, 0x39, 0x91, 0x9f, 0xcb, 0xeb, 0x68, 0x0a, 0xc9, 0x07, 0x84, 0xa0, 0x68, 0x03, 0xcb,
	0xff, 0x65, 0x40, 0x08, 0xf2, 0x3e, 0xf0, 0x2a, 0x54, 0x58, 0x1c, 0xab, 0x76, 0x51, 0x93, 0x72,
	0xfd, 0x38, 0xa6, 0x88, 0x92, 0x0f, 0xa1, 0x2e, 0xdb, 0x51, 0x75, 0xb1, 0xf6, 0x6a, 0xff, 0x49,
	0x15, 0x8f, 0xdc, 0x81, 0x46, 0x28, 0x3b, 0x0e, 0x71, 0xb9, 0x62, 0x3b, 0xd5, 0x86, 0xd0, 0x9c,
	0x8b, 0x7b, 0x4d, 0xe3, 0x54, 0x35, 0x90, 0x5a, 0x51, 0x0d, 0x29, 0xa2, 0xb8, 0x97, 0xb4, 0xb4,
	0xea, 0x1c, 0xd5, 0x5e, 0xd2, 0x87, 0x54, 0xf1, 0xc8, 0x4d, 0x68, 0x06, 0xa9, 0xeb, 0xf3, 0xa3,
	0xc5, 0x54, 0x74, 0xfd, 0xcd, 0x87, 0xb5, 0x17, 0x6c, 0x96, 0x72, 0xda, 0x08, 0xd2, 0x21, 0xa2,
	0x24, 0x82, 0xed, 0xdc, 0x3e, 0x62, 0x9c, 0xf3, 0xa2, 0x99, 0x2c, 0xc2, 0x9a, 0x78, 0xe1, 0x77,
	0xa4, 0xda, 0x35, 0x9b, 0xee, 0xaa, 0xdf, 0xb1, 0x92, 0xc7, 0xca, 0xf8, 0x90, 0x3c, 0x71, 0x9c,
	0xb1, 0x3b, 0xa6, 0xb6, 0x63, 0x0f, 0xec, 0x91, 0x68, 0x2b, 0xe8, 0x85, 0xe4, 0x6d, 0x41, 0xec,
	0x8b, 0x63, 0x9c, 0xad, 0x60, 0x35, 0x74, 0xf0, 0x59, 0x51, 0x81, 0xf7, 0x18, 0x5c, 0x78, 0x87,
	0x7e, 0x72, 0x19, 0xb6, 0xf3, 0x7e, 0x64, 0x6d, 0x13, 0x7d, 0x03, 0xfb, 0xa7, 0xb7, 0x37, 0xd7,
	0x4b, 0x64, 0x07, 0x2e, 0x20, 0x3e, 0x39, 0xc7, 0x28, 0xf7, 0x0e, 0x40, 0x3b, 0xe0, 0x19, 0x33,
	0x43, 0x9f, 0xbf, 0xc6, 0x70, 0xcf, 0xa2, 0x8c, 0xcd, 0xdc, 0x70, 0x31, 0x97, 0x23, 0x0b, 0x6d,
	0x0a, 0xc0, 0x5a, 0xcc, 0xc5, 0xc3, 0x5a, 0x24, 0x89, 0x78, 0xa2, 0x28, 0xad, 0x32, 0x63, 0x5b,
	0x81, 0x42, 0x43, 0xef, 0x7b, 0x1a, 0xb4, 0xf3, 0xec, 0x82, 0x7a, 0xc9, 0x10, 0x3a, 0x5e, 0xc2,
	0x59, 0x16, 0xbc, 0x5c, 0x6b, 0x68, 0x6e, 0x28, 0x5b, 0xae, 0x88, 0xee, 0x0e, 0x94, 0x9c, 0xec,
	0x39, 0xbd, 0x15, 0x8a, 0x1c, 0x80, 0x1e, 0x84, 0x19, 0x4f, 0xd8, 0x5b, 0xcd, 0x6f, 0xef, 0x1d,
	0x8a, 0xcc, 0xa5, 0xa8, 0xd0, 0xb5, 0x15, 0xac, 0x03, 0xe4, 0x43, 0xd8, 0x7c, 0x15, 0x84, 0x6e,
	0x18, 0x65, 0x41, 0x91, 0x90, 0xb0, 0x95, 0x68, 0xbf, 0x0a, 0x42, 0x4b, 0x80, 0x98, 0x93, 0xae,
	0x82, 0xe6, 0xcd, 0x02, 0xef, 0x44, 0x08, 0xc8, 0x94, 0xd4, 0x14, 0xc0, 0xe1, 0x6a, 0x96, 0xab,
	0xad, 0x66, 0xb9, 0x9b, 0x38, 0xb0, 0xa5, 0x5e, 0x12, 0xc4, 0xb8, 0x97, 0x4a, 0x3d, 0xab, 0x10,
	0xb9, 0x0c, 0xcd, 0xc0, 0x8b, 0x42, 0x37, 0x4d, 0xbc, 0x6e, 0x43, 0x6c, 0xda, 0x40, 0x7a, 0x92,
	0xe0, 0x18, 0xac, 0x05, 0x73, 0x36, 0xe5, 0x82, 0xd7, 0x14, 0xbc, 0xa6, 0x00, 0x90, 0x79, 0x6e,
	0x1a, 0xd7, 0xce, 0x4f, 0xe3, 0xa8, 0x18, 0x05, 0x44, 0x2a, 0x02, 0xe1, 0x99, 0x06, 0x8b, 0x63,
	0x91, 0x7b, 0xae, 0x82, 0x26, 0x32, 0x89, 0xb8, 0x48, 0x4b, 0x5e, 0x44, 0x00, 0x78, 0x91, 0xdb,
	0xb0, 0x29, 0x99, 0xfe, 0x22, 0x61, 0xe2, 0xd4, 0x6d, 0x59, 0xf1, 0x04, 0x3a, 0x54, 0x20, 0xd9,
	0x05, 0x98, 0xf3, 0x8c, 0x29, 0xd7, 0x77, 0x44, 0xc0, 0x6e, 0x29, 0xdb, 0xe7, 0xf1, 0x43, 0xb5,
	0x79, 0x11, 0x4a, 0xb7, 0xa1, 0xa8, 0x5c, 0xae, 0x1c, 0x81, 0x37, 0xa5, 0xda, 0x1c, 0x7d, 0x2e,
	0xe6, 0xe0, 0x3b, 0x2b, 0x35, 0x51, 0x0d, 0xc4, 0x5b, 0x42, 0xae, 0x58, 0xfd, 0x44, 0xa0, 0x98,
	0xbb, 0x8e, 0x12, 0x16, 0xfa, 0x72, 0xb8, 0xd2, 0x65, 0xee, 0x12, 0x88, 0x98, 0xaf, 0xf0, 0xf6,
	0xbe, 0x2b, 0x3d, 0xf2, 0x9e, 0x60, 0x36, 0x98, 0xef, 0x08, 0x9f, 0x7c, 0x00, 0xc5, 0x9e, 0xd2,
	0x3a, 0x44, 0xc6, 0x6d, 0x0e, 0x0a, 0x13, 0xdd, 0x82, 0xb6, 0xcf, 0x79, 0x3c, 0x0b, 0x42, 0xe9,
	0xee, 0x0b, 0xc2, 0xab, 0xad, 0x1c, 0x43, 0x43, 0x7d, 0x00, 0x9d, 0x17, 0x6c, 0x36, 0x3b, 0x62,
	0xde, 0x89, 0x0c, 0xc0, 0x8b, 0x52, 0x4f, 0x0e, 0x8a, 0xc8, 0xba, 0x05, 0x05, 0x2d, 0xf4, 0x6c,
	0x4b, 0x3d, 0x39, 0x86, 0x7a, 0x84, 0xa3, 0x4e, 0xe4, 0x3d, 0x2e, 0xa9, 0xa3, 0xc6, 0x27, 0xe2,
	0x16, 0x97, 0xa0, 0x8e, 0xe6, 0x0e, 0xa7, 0xdd, 0x9d, 0x9b, 0xa5, 0xbb, 0x65, 0xaa, 0x28, 0x6c,
	0xdb, 0xbd, 0x68, 0x3e, 0xe7, 0x61, 0x96, 0x76, 0xbb, 0xf2, 0x59, 0xe6, 0x34, 0xf9, 0x06, 0x80,
	0x8a, 0x1a, 0xbc, 0xdb, 0x65, 0xe1, 0x98, 0x6b, 0xef, 0x7a, 0x14, 0x22, 0x92, 0xb0, 0x2c, 0xc9,
	0x28, 0xc3, 0xcf, 0x2b, 0x9f, 0x80, 0x56, 0xe0, 0x18, 0xd2, 0x2b, 0x7f, 0x56, 0xe4, 0xff, 0x54,
	0x5c, 0x5a, 0xff, 0xa7, 0xa2, 0xf8, 0x9b, 0xe2, 0x53, 0x68, 0xaf, 0x3e, 0x58, 0xec, 0x45, 0x2c,
	0x3b, 0x4f, 0x43, 0x4d, 0xa8, 0x3a, 0xc6, 0x67, 0x8e, 0x1c, 0x0d, 0xcc, 0x03, 0x6c, 0x63, 0xcb,
	0xa4, 0x03, 0x1a, 0x82, 0xae, 0x39, 0xb0, 0x2d, 0xd9, 0x61, 0x8b, 0x86, 0x42, 0xaf, 0xf6, 0x2c,
	0xd8, 0x3a, 0xf7, 0x66, 0x71, 0x4c, 0xb2, 0x6c, 0xd7, 0xb4, 0x1c, 0x83, 0xf6, 0xc5, 0x30, 0xa8,
	0x6f, 0xe0, 0x16, 0x93, 0x43, 0xfa, 0xd8, 0xb4, 0xf6, 0x65, 0xe3, 0x5e, 0xf4, 0xc2, 0xa2, 0xc5,
	0x19, 0x1a, 0xc6, 0x78, 0x64, 0x5a, 0x4f, 0xf5, 0x4a, 0xef, 0x67, 0x55, 0x28, 0xf7, 0xfd, 0x2f,
	0xaf, 0xde, 0xb7, 0xa0, 0x7d, 0x9c, 0xcd, 0x67, 0x6e, 0x1a, 0x06, 0x71, 0xcc, 0x33, 0xd5, 0xad,
	0xb4, 0x10, 0x9b, 0x48, 0x88, 0x7c, 0x7d, 0x25, 0x72, 0x30, 0xb2, 0x55, 0xa9, 0x23, 0x6f, 0x5b,
	0x77, 0x19, 0x4d, 0x22, 0xe9, 0x6d, 0x63, 0x41, 0x72, 0xb1, 0x64, 0x57, 0xd5, 0x3f, 0x06, 0xfe,
	0x53, 0x7e, 0x4a, 0xbe, 0x8a, 0x0d, 0x83, 0x9b, 0x8f, 0x2b, 0x6a, 0x36, 0xde, 0x5c, 0x9f, 0x80,
	0xb0, 0x69, 0x28, 0xa6, 0xa6, 0xaf, 0xa9, 0x47, 0x37, 0x4d, 0xa2, 0x45, 0x2c, 0xb2, 0xc9, 0xbb,
	0x77, 0x17, 0xef, 0x6e, 0x1f, 0x85, 0xf0, 0x9d, 0xcc, 0xa3, 0x23, 0x97, 0xf9, 0x19, 0x7f, 0x9d,
	0xa9, 0xd6, 0x46, 0x9b, 0x47, 0x47, 0x7d, 0x01, 0x2c, 0xd9, 0xb3, 0x68, 0x1a, 0xc9, 0x3f, 0xbf,
	0x14, 0x1b, 0x01, 0xb2, 0x03, 0x0d, 0x2f, 0x9e, 0xbb, 0x47, 0x81, 0x2f, 0x32, 0x4c, 0x87, 0xd6,
	0xbd, 0x78, 0xfe, 0x28, 0xf0, 0xb1, 0xcd, 0x9b, 0xfb, 0x0f, 0xe4, 0x3f, 0x5d, 0x14, 0x3f, 0x45,
	0x42, 0x92, 0xc6, 0x15, 0x8f, 0xa1, 0x25, 0xfb, 0x0f, 0x09, 0x15, 0xff, 0x13, 0x1c, 0xb3, 0x64,
	0xaa, 0xf2, 0xbe, 0xcc, 0x2a, 0x20, 0x21, 0x55, 0xc6, 0x9a, 0x47, 0x8b, 0x53, 0x2e, 0x7a, 0xb0,
	0x8e, 0xcc, 0x58, 0x82, 0x36, 0x7d, 0xf1, 0x46, 0xc2, 0x2c, 0x70, 0x33, 0x36, 0x15, 0x79, 0xa3,
	0x46, 0x1b, 0x48, 0x3b, 0x6c, 0x2a, 0x1a, 0xc9, 0x8c, 0x25, 0x99, 0x8b, 0xb3, 0xa9, 0x48, 0x16,
	0x55, 0xaa, 0x09, 0xc4, 0x09, 0x64, 0x22, 0xe0, 0xa1, 0x2f, 0x99, 0xba, 0x60, 0x36, 0x78, 0xe8,
	0x23, 0xab, 0xf7, 0x9b, 0x12, 0x6c, 0xe6, 0xc5, 0x3b, 0x8d, 0xa3, 0x30, 0xe5, 0xff, 0xab, 0x23,
	0xba, 0x0e, 0xc0, 0x93, 0x24, 0x4a, 0x5c, 0x2f, 0x52, 0xd3, 0x74, 0x95, 0x6a, 0x02, 0x19, 0x44,
	0x62, 0x9a, 0xae, 0x30, 0x5f, 0x36, 0x74, 0xad, 0xbd, 0x66, 0xde, 0x74, 0x50, 0x04, 0x31, 0xb1,
	0xf1, 0xd7, 0x71, 0x20, 0xb3, 0xa7, 0x3c, 0x8e, 0x9c, 0xa9, 0x37, 0x97, 0xb0, 0x38, 0x30, 0xde,
	0x87, 0xb3, 0xc4, 0x3b, 0x76, 0x97, 0x2d, 0x9e, 0x26, 0x11, 0x8c, 0x99, 0xab, 0xa0, 0xf1, 0xd7,
	0x99, 0x9b, 0x66, 0xa7, 0x33, 0x2e, 0xda, 0x9f, 0x36, 0x6d, 0xf2, 0xd7, 0xd9, 0x04, 0xe9, 0xff,
	0x04, 0x00, 0x00, 0xff, 0xff, 0x62, 0x5a, 0x6c, 0x04, 0x7b, 0x16, 0x00, 0x00,
}
